### ISSUE TITLE
Unicode characters are not encoded right

### ISSUE THREAD

**Issue by pstuifzand** [swentel/indigenous-android#103]
**Describe the bug**
Items with unicode characters, don't have the right characters rendered.

**To Reproduce**
1. Look at entry with unicode characters.

**Expected behavior**
Unicode characters should be rendered with the right encoding.

**Screenshots**
![screenshot_20180908-153905](https://user-images.githubusercontent.com/64524/45254846-716d3100-b37f-11e8-9507-200210f7d893.png)

**Smartphone (please complete the following information):**
 - Device: Nokia 6
 - Android version: 8.1.0

**Additional context**

**Comment by swentel** [comment]
Interesting. I have seen emoticons being rendered fine in my streams, so I wonder whether this is not a feed (import/export) problem rather than a problem in Android itself.

Do you have a feed which is more 'public' which also has this problem so I can reproduce ?

**Comment by pstuifzand** [comment]
I found this in the https://chat.indieweb.org/dev feed. I see this in all feeds with unicodes characters. I don't have this problem in any of the web based readers (like together, monocle, my own).
I'm trying this now with Aperture as well, but I can't see the channels now.

**Comment by pstuifzand** [comment]
I have tracked down the issue to a difference in encoding of the feed. There seems to be difference in the handling of the json input file, when it's UTF-8 characters and when the characters are encoded as escape sequences like \u0000.

Aperture encodes the json file with escape sequences and [Ekster](https://github.com/pstuifzand/ekster) uses UTF-8 characters. As far as I know, both are acceptable JSON. So it seems somewhere when calling the API there is a charset conversion going on. I hope you have an idea, where to look. I'll also try to look for it.

**Comment by pstuifzand** [comment]
This seems to be a problem for other people: https://stackoverflow.com/questions/27932123/utf-8-encoding-in-volley-requests

I'll make a change to the server and send the file with content-type: application/json; charset=UTF-8.

**Comment by pstuifzand** [comment]
Changing the `Content-Type` to `application/json; charset=utf-8` solved the problem for me. So it seems the default charset is something different from utf-8 in the volley request. I'm not sure if this is expected behavior, or that it should be seen as a problem in the server.

**Comment by swentel** [comment]
I'm seeing chars not being encoding right from my microsub server as well, (although limited) although it's still in early stages. Might be a problem on the PHP side as well, but I can do some double checks now!

**Comment by swentel** [comment]
I haven't seen this anymore at my side, so leaving as is since the workaround/fix is easier on the server side for now :)
