### ISSUE TITLE
Prettify dates, localize and fix hour notation

### ISSUE THREAD

**Issue by swentel** [swentel/indigenous-android#108]
There are a couple of libraries which allow you to easily render dates as 'x minutes ago' etc, much nicer experience.

Also, sometimes I see hours like 24:33 - that's not right

**Comment by dshanske** [comment]
For Micropub, I would want the published date to be sent with the local timezone offset so I could tell what time it was where I posted

**Comment by swentel** [comment]
Ok following dates are accepted: 
"yyyy-MM-dd'T'kk:mm:ssZ", "yyyy-MM-dd kk:mm:ssZ", "yyyy-MM-dd kk:mmZ"

Haven't seen the hour problem anymore so far, so that's fine I guess.
going to leave the 'x minutes/hours ago' out for now.
