### ISSUE TITLE
New Media Addition

### ISSUE THREAD

**Issue by dshanske** [swentel/indigenous-android#110]
The new media type is erroring out on my media endpoint. I tested Quill, for example, and it does find and use the media endpoint.

**Comment by swentel** [comment]
Hmm, so the media activity only shows up if the media endpoint is found after refreshing configuration, so it has that at least. Is it a 500 on the server then ?

**Comment by dshanske** [comment]
Correct

**Comment by swentel** [comment]
Do I use the micropub plugin or indieweb ?

**Comment by dshanske** [comment]
Only the GitHub repo has a media endpoint

**Comment by swentel** [comment]
So the request comes through, and $file looks like this after it's handled by wp_handle_upload(), and then errors out on the error array.

Can't debug further today, more tomorrow.

```
Array
(
    [name] => Array
        (
            [0] => 1537114072016.jpg
        )

    [type] => Array
        (
            [0] => 
        )

    [tmp_name] => Array
        (
            [0] => /tmp/phpqM3tbu
        )

    [error] => Array
        (
            [0] => 0
        )

    [size] => Array
        (
            [0] => 207723
        )

)
```

**Comment by dshanske** [comment]
I will try to add a check for this.

**Comment by swentel** [comment]
Not necessary anymore, I have it working. And still works fine with the Drupal endpoint.
Will push a new release in a few minutes.

**Comment by dshanske** [comment]
swentel++

**Comment by swentel** [comment]
Release pushed, thanks for the report. I now have a local wordpress install now too, so I can start testing on more environments, so more wins :)

**Comment by dshanske** [comment]
Confirmed this works. Now I just need to get the new version out to everyone from Github.
