### ISSUE TITLE
Error returned from Micropub endpoint when using syndication target

### ISSUE THREAD

**Issue by ngm** [swentel/indigenous-android#112]
I quickly [hacked together a syndication target](https://gist.github.com/ngm/20d98e724f7452912942cc4dc401a761) for my Wordpress Micropub endpoint, to syndicate to Mastodon, via the [Mastodon Autopost](https://github.com/simonfrey/mastodon_wordpress_autopost) plugin.  I *think* it's working OK (despite the hackiness), as it works OK via quill, and it works OK via `shpub` with:

```
shpub note "Foo barrio" -x mp-syndicate-to=social_coop
```
It appears correctly as a syndication target in Indigenous, however when I select it as a syndication target when creating a note, I get the following error message back:

> Unknown mp-syndicate-to targets: Array

which I think is coming from this line in the WP Micropub plugin: https://github.com/indieweb/wordpress-micropub/blob/master/includes/class-micropub-endpoint.php#L242

Quick possible something is going wrong somewhere else in the chain, but the fact that it works from shpub and quill is interesting.  I have two syndication targets - a Twitter target provided by Bridgy Publish, and the Mastodon one.  The Bridgy Publish target **does** work from Indigenous.

**To Reproduce**
1. Have Wordpress site
2. Setup WP Micropub plugin
3. Setup Mastodon Autopost plugin
4. [Hack together syndication to Mastodon](https://gist.github.com/ngm/20d98e724f7452912942cc4dc401a761)
5. Refresh syndication targets in Indigeneous
6. Post a note, selecting the Mastodon syndication target

**Expected behavior**
Post created on my site, and syndicated to my Mastodon instance.

**Smartphone:**
 - Device: Sony Xperia Z1 Compact
 - Android version: 5.1.1

**Comment by ngm** [comment]
Extra bit of info - if when creating a note in Indigenous, I select the Bridgy Publish syndication target, but don't select my Mastodon target, it syndicates to both Twitter and Mastodon (expected behaviour: only syndicate to Twitter).

**Comment by dshanske** [comment]
I can help you with this, but it isn't an Indigenous problem

**Comment by swentel** [comment]
Hmm, I haven't tried sending two targets actually.

Are you able to check two things:

1. How does q=config response look like with the syndication targets
2. How does the request from indigenous look like when it goes to the server

**Comment by ngm** [comment]
Thanks for the help!

> I can help you with this, but it isn't an Indigenous problem

@dshanske Hmm, but how come it is working via Quill and shpub?

> Hmm, I haven't tried sending two targets actually.

@swentel  In this case I'm actually only trying to send to one target, although I have two configured.

I'll send through the extra info later today when I'm back from work.  Thanks!

**Comment by ngm** [comment]
Bit more context:

> if when creating a note in Indigenous, I select the Bridgy Publish syndication target, but don't select my Mastodon target, it syndicates to both Twitter and Mastodon (expected behaviour: only syndicate to Twitter)

This was a bug in my `micropub_syndicate-to` filter method - I was doing a string comparison with == rather than === which is apparently [a no-no in PHP](https://stackoverflow.com/questions/3333353/string-comparison-using-vs-strcmp)!

If I remove the Bridgy Publish syndication target from my configuration altogether, then selecting the Mastodon target when creating a note does syndicate correctly to Mastodon.

So it could be an issue with having multiple targets configured?  Or very possibly could also be an issue somewhere in my target code.

**Comment by ngm** [comment]
> How does q=config response look like with the syndication targets from your micropub endpoint

```
{
  "syndicate-to": [
    {
      "uid": "bridgy-publish_twitter",
      "name": "Twitter via Bridgy Publish"
    },
    {
      "uid": "social_coop",
      "name": "social.coop"
    }
  ]
}
```

> How does the request from indigenous look like when it goes to the server

[Tue Sep 18 20:51:24.571870 2018] [dumpio:trace7] [pid 27174] mod_dumpio.c(103): [client 92.15.226.34:53201] mod_dumpio:  dumpio_in (data-TRANSIENT): --apiclient-1537303886977
Content-Disposition: form-data; name="mp-syndicate-to[1]"

social_coop
--apiclient-1537303886977
Content-Disposition: form-data; name="post-status[0]"

published
--apiclient-1537303886977
Content-Disposition: form-data; name="content"

tester
--apiclient-1537303886977
Content-Disposition: form-data; name="access_token"

[redacted]
--apiclient-1537303886977
Content-Disposition: form-data; name="h"

entry
--apiclient-1537303886977--

**Comment by swentel** [comment]
Thanks for that info. syndicate-to looks good. In the post request, mp-syndicate-to is an array, so maybe it's tripping over that in PHP somehow because the index key is set to 1. Will test with my local install on both drupal and wordpress to see what happens.

**Comment by swentel** [comment]
> This was a bug in my micropub_syndicate-to filter method

So is this different code than the wordpress code filtering then (apply_filters maybe?) ? I can't seem to reproduce the problem for now.

**Comment by ngm** [comment]
> so maybe it's tripping over that in PHP somehow because the index key is set to 1

Yes sounds plausible.

> I can't seem to reproduce the problem for now.

I'll try and dig into it further and find where the problem lies when I get chance.  I'm good for now as is, as I don't actually want to syndicate to Twitter, and all is working when I've just got the Mastodon target by itself.  Thanks for your help!

**Comment by swentel** [comment]
Good news, depending on how you look at it :) 
I could reproduce this now too. I could fix it in my endpoint, but that's cheating. 
Will post a fix soon for Indigenous!

**Comment by swentel** [comment]
Aaaaand fixed. Will be available in next release.
