### ISSUE TITLE
Make available on https://f-droid.org/

### ISSUE THREAD

**Issue by swentel** [swentel/indigenous-android#119]

**Comment by swentel** [comment]
Hmm I've tried this and it didn't work decent at all. I'll keep uploading the binaries to github. I might add release checker maybe one day that pings github.

**Comment by swentel** [comment]
going to reopen this, will do another test

**Comment by swentel** [comment]
Opened an issue at https://gitlab.com/fdroid/rfp/issues/880

**Comment by swentel** [comment]
Done ! :)

https://f-droid.org/en/packages/com.indieweb.indigenous/

**Comment by licaon-kter** [comment]
@swentel Are versions newer than 0.34 going to be released: https://github.com/swentel/indigenous-android/tags ?

**Comment by swentel** [comment]
Weird, I really though I pushed one, seems like I missed something.
Will check again this week, probably friday (on the road now)

**Comment by swentel** [comment]
Quite update: I've tested the latest build on my LineageOS phone and everything seems to be working fine, including push notification via Pushy.me. I'm currently testing some new features as well which I want to make sure the are fine, so a new release will be in a week - I've set it to release on november 9 around 11am.

(location is still not available though, that will be for another release)

**Comment by swentel** [comment]
new released tagged actually, yay!
