### ISSUE TITLE
Offline reading (caching)

### ISSUE THREAD

**Issue by ngm** [swentel/indigenous-android#120]
What I've seen referred to on [Tantek's page](https://indieweb.org/User:Tantek.com#itches) as COOLPOSSE - captured/created offline, optional later posting to own site syndicating elsewhere.

For me I quite often read & take notes when I'm on the tube, where there's no signal (I don't want to use the free wifi they provide ;) ).  At the moment I manually syndicate my bookmarked posts to Wallabag, so I'll read them in that when offline, and the notes that I take I save in a different app (Orgzly) and make a todo to remember to post them later.

A very low priority I would imagine, given it's probably complex to do, and it's an infrequent use case.  But still - would be cool one day!

**Comment by dshanske** [comment]
I don't think it would be for posting. It is just saving the data.

**Comment by swentel** [comment]
I have #43 for offline posting, so I think that's kind of the same. It's something I'd like to have as well and that's actually a target for the next release :)

As for reading. I've been thinking about that as well already and it should be relatively easy - at least in my head :). Even images will work offline if they have been fetched once already. Not sure when this might get in, thery may be dragons. I'm going to check with the iOS client as I think it has that built in as well IIRC.

**Comment by swentel** [comment]
renamed the title a bit - renamed #43 as well

**Comment by EdwardHinkle** [comment]
Just FYI about iOS version. I have offline caching of the channels but not the actual posts (yet). But it’s definitely on the roadmap at some point

**Comment by swentel** [comment]
@ngm save as draft is in for notes, articles and replies - released, so available soon :)

**Comment by swentel** [comment]
I'm not going to start with offline caching, way to hard to implement decently, and let's be honest, you're usually online anyway.
