### ISSUE TITLE
Items not loaded

### ISSUE THREAD

**Issue by argovaerts** [swentel/indigenous-android#123]
Items don't load.
Error: no value for _id

Microsub server is [Baffle](https://github.com/snarfed/baffle) (with Newsblur in the back).
Site: tglo.be

To make sure it's not a mistake in my piping I tested this in Monocle as well. Everything fine there.

**Comment by swentel** [comment]
Hmm interesting, I see the _id property https://github.com/snarfed/baffle/blob/master/routes/newsblur.js#L235 so not sure what happens here.

Can you check in monocle and hit 'Debug' and see how the json looks like ?

**Comment by swentel** [comment]
So my guess is that the property is set, but will be empty.
In a way that's a kind of bug in Baffle, but I can account for that as it's not /that/ of a big deal :)

**Comment by snarfed** [comment]
interesting! newsblur seems to have dropped its `story_id` field from its API completely, which we use as microsub `_id`. not sure if that's intentional or a bug. i'll ping them.

**Comment by snarfed** [comment]
[reported here.](https://forum.newsblur.com/t/api-story-id-field-dropped-from-story-objects/7160)

**Comment by argovaerts** [comment]
> 
> 
> So my guess is that the property is set, but will be empty.
> In a way that's a kind of bug in Baffle, but I can account for that as it's not /that/ of a big deal :)

Not set. Strange.

**Comment by swentel** [comment]
I've pushed a new release of the app which should load the items.
If there's no id, the 'mark as read' function will not work either, but that's less of a problem.
