### ISSUE TITLE
"Error: No value for unread"

### ISSUE THREAD

**Issue by cleverdevil** [swentel/indigenous-android#129]
**Describe the bug**
After logging in with [my website](cleverdevil.io), I get an error that says "Error: No value for unread," which also happens if I tap "refresh channel list."

**To Reproduce**
1. Launch the app
2. Wait or tap on "refresh channel list."
3. See error

**Smartphone (please complete the following information):**
 - Device: GPD XD+
 - Android version: Latest version of [Clean ROM](https://www.black-seraph.com/project/cleanrom-for-gpd-xd/) which I believe is Android 7.0.

**Comment by swentel** [comment]
Interesting, you are on the same instance as me, so it's a bug in aperture somehow.
However, failing so hard is kind of stupid, so I can fix that quite easily.

One way to check which channel has an empty or null 'unread' value, is to test with monocle, inspect the ajax request with url 'reload?format=json' in it and check the response.

**Comment by cleverdevil** [comment]
Yup, using `curl`, I am able to see the output from `reload?format=json`, and I have two channels that have no "unread" property. I don't think this is a bug in Aperture, actually. I have explicitly configured those two channels not to track unread status within Aperture (this is a feature), hence why it isn't returning that property.

I am guessing all that is needed on your end is to assume unread is 0 if no property is found.

**Comment by swentel** [comment]
Yes, you're right, it's broken now here too when I change that setting, great catch! Will fix that tomorrow!
