### ISSUE TITLE
Location Visibility Appearance

### ISSUE THREAD

**Issue by dshanske** [swentel/indigenous-android#131]
Love the new feature, but the presentation is unclear. What about putting the location icon next to it?

**Comment by swentel** [comment]
Oh that makes sense indeed. I'm not entirely happy with the spinner either as you can't see the title/prompt so I want to change that for all select boxes in the app as well.

**Comment by dshanske** [comment]
Design is hard

**Comment by swentel** [comment]
I've made it a bit clearer by adding an explicit title.
This will get another iteration in #133 as too.
