### ISSUE TITLE
Render more properties from q=source 

### ISSUE THREAD

**Issue by grantcodes** [swentel/indigenous-android#132]
Was just trying out the posts list query and although it grabbed my list of posts, it didn't handle formatting them very well. This may be a case of supporting displaying more property types, or there might be some mf2 to jf2 conversion you can do to improve the display of the posts

So far I have noticed the following properties are hidden:
- `summary`
- `featured`
- `like-of`
- `bookmark-of`
- `photo`
- `category`
- `published`
- `visibility`
- `post-status`

Also since I return an object with `html` and `value` in the `content` property, that is not rendered correctly.

**Expected behavior**
I wouldn't expect indigenous to support rendering and editing all of these properties, although the most important ones personally would be `post-status`, `photo`, `category`, `visibilty` and fixing `content`. And on the post list if the post would end up being rendered as blank like in my screenshot, it should at least show the url.

I would also like to see that data in the edit screen, not a blank form. And I think the form should show all unrecognized properties properties (just as json is fine), so that you know you aren't going to lose any data. I was a bit worried about actually doing an update as I don't know if it is going to replace everything or just the new content I write.

**Screenshots**
![screenshot_20181015-105751_1](https://user-images.githubusercontent.com/3390268/46940624-73569e00-d069-11e8-9e1f-7c72c66c1019.jpg)

**Comment by swentel** [comment]
I wonder if it's fine to ellipsize the content to say 2 lines or so ?

As for the current update screen: this is related to https://github.com/swentel/indigenous-android/issues/114 - I don't have support for that yet in the client, so clicking on update passes on the url and that's it.

When you would hit the send button on an update screen, only the properties which are not empty, except for the post status are send along in the payload. However, I agree, it's currently not optimal at all :) In the end, the goal is that the proper 'post' screen is selected, with all values pre-populated, so I need to do some post-type discovery first.

I'll be working on this towards Berlin, so I hope to get it finished by then!

**Comment by grantcodes** [comment]
Perfect, sounds like a good plan.

Feel free to let me know if you want some testing, I think I might be the only other android user that supports all these micropub query features at the moment :P

**Comment by swentel** [comment]
There's a new release. It's rendering some more properties already, but it's not fully done yet, stay tuned :)

**Comment by dshanske** [comment]
I also have the content problem with returning an object @grantcodes mentioned

**Comment by swentel** [comment]
Working on this a bit, both on the Drupal side, and then here: the content object, is it inside an array also ? or not. Same for the author basically.

**Comment by swentel** [comment]
Baby steps: the overview now handles content when the first key in the array is

- a string
- or an object with 'text' and 'html'. I render the text version at the moment as my current goal for this in indigenous is just to get a quick overview of the posts on my site.

Next step is update: getting the right post screen and calling q=source&url={url}

This fix will probably will come in a release in a few days already though.

**Comment by swentel** [comment]
Data is fetched from the server now for an update. Closing this for now, it's fine for my use case at the moment.  Other properties are way more complex, at that point, I have my content more easily updated in my cms ;)
