### ISSUE TITLE
Feature Request: Reverse Geolocation

### ISSUE THREAD

**Issue by dshanske** [swentel/indigenous-android#133]
This isn't a bug report. It is a feature request, but there isn't an option for that...

https://developer.android.com/training/location/display-address 

Would like to propose that the location property optionally does reverse geocoding. It can send a more detailed location property...

Specifically, the location property can be, if you use json encoding, a nested h-adr with the coordinates and details on the location.

I've been doing this on the backend, but Android has a native integration for it, it looks like.

**Comment by swentel** [comment]
Oh wow, this is cool. I always thought you'd need an external service for this, although I can imagine, geocoder probably connects with Google .. :)

(ps: I've added the feature request template as well)

**Comment by dshanske** [comment]
As a follow up to this, what about an optional textbox for a textual location description as a precursor to trying to figure it out yourself?

**Comment by dshanske** [comment]
The property is location for textual address, but if you also have coordinates you would need a nested h-adr.

**Comment by dshanske** [comment]
What if I implement a Micropub query for the location name?

**Comment by dshanske** [comment]
So you can query the endpoint?

**Comment by swentel** [comment]
So that the endpoint does the reverse geolocation based on coordinates ? That might be an option yes, especially for phones that do not support it. But let me get it working natively first.

**Comment by dshanske** [comment]
I have the functionality, I just have to tie it to the query as outlined in the https://indieweb.org/Micropub-brainstorming#Query_for_places

**Comment by dshanske** [comment]
https://github.com/indieweb/micropub-extensions/issues/6 

I've outlined the return I've implemented in the above issue. You can query by uri=geouri or lat=&lon= and it will return a venue and a geo property. I'm only returning the geo property, which contains a name property for the suggested name right now.

**Comment by swentel** [comment]
Ok, there's now an optional label field and a query button to search on q=geo.

If there's a location name, it's appended to the geoUri:

```
geo:51.019903,3.7716038,0.0;name=Melle Vogelhoek
```

It's a setting underneath 'Posts' to expose two new features.

**Comment by swentel** [comment]
will release tomorrow!

**Comment by dshanske** [comment]
Yay!!
