### ISSUE TITLE
Pass Altitude Data if Available

### ISSUE THREAD

**Issue by dshanske** [swentel/indigenous-android#135]
**Is your feature request related to a problem? Please describe.**
I would like to store altitude data from the phone if available.

**Describe the solution you'd like**
If altitude data is provided by the Android location provider, pass it along. The Geo URI scheme allows for passing a third parameter if available.

https://en.wikipedia.org/wiki/Geo_URI_scheme#Example

**Describe alternatives you've considered**
Generating the data based on an elevation API when not provided.

**Comment by swentel** [comment]
So, it should be something like geo:lat,lon,alt right ?

**Comment by dshanske** [comment]
Correct

**Comment by swentel** [comment]
Interesting, if I do that, then I get an altitude in the app too. The status app tells me that I'm 9m above sea level, the value I get in the app is something along 61.xxxx but that seems to be a different height (WGS84 reference ellipsoid). Will have to look up how to convert that.

**Comment by dshanske** [comment]
Don't worry too much about it

**Comment by swentel** [comment]
yeah maybe not. Pushed, will be available in next release. We can always finetune later.

**Comment by dshanske** [comment]
https://github.com/mendhak/gpslogger/issues/658 Related

**Comment by dshanske** [comment]
https://github.com/mendhak/gpslogger/issues/658 Related

**Comment by dshanske** [comment]
I can't wait to test this at altitude

**Comment by swentel** [comment]
I'll release a new version on friday so I can concentrate on more bigger things after that now that I have my own microsub server running.
