### ISSUE TITLE
Allow name to be passed to media endpoint

### ISSUE THREAD

**Issue by dshanske** [swentel/indigenous-android#143]
Because I like to name my photos.

**Comment by swentel** [comment]
Which property do I need to send exactly? (I guess 'name') 
I remember once reading it, but can't find it anymore.

**Comment by dshanske** [comment]
There is no official notation re this. https://www.w3.org/TR/micropub/#media-endpoint

**Comment by dshanske** [comment]
But passing a name would allow querying the endpoint by name in future

**Comment by swentel** [comment]
This is a setting now in 'Media'. It allows to expose a textfield where you can enter a name then. Defaults to false. The post key is 'name'.
