### ISSUE TITLE
Search for experimental media endpoint rel

### ISSUE THREAD

**Issue by dshanske** [swentel/indigenous-android#145]
https://indieweb.org/micropub_media_endpoint#Discovery_via_link_rel

**Comment by swentel** [comment]
Currently I'm getting this via q=config 

Forgot that there was a rel too.

**Comment by dshanske** [comment]
It's a new proposal

**Comment by swentel** [comment]
Oh ok, mixing things then. However, makes much sense to make media endpoint less coupled with micropub.

**Comment by swentel** [comment]
Link tag should be fine.

Finding it from header is for https://github.com/swentel/indigenous-android/issues/148
