### ISSUE TITLE
Support query last for Media endpoints

### ISSUE THREAD

**Issue by dshanske** [swentel/indigenous-android#146]
https://indieweb.org/micropub_media_endpoint#Query_the_last_thing_uploaded

**Comment by swentel** [comment]
Where can this be used then ?

**Comment by dshanske** [comment]
To suggest the last image uploaded to the endpoint for a photo or note post. Quill uses it

**Comment by swentel** [comment]
right, but then, instead of sending it in $_FILES, it's just a photo property with the url in it ?

**Comment by dshanske** [comment]
Correct. I don't currently implement it, but it is on my list for implementation. My challenge is criteria. Do I limit it only to Micropub uploads or not?

**Comment by swentel** [comment]
I don't implement it either at the moment, and it's very low on my priority list.

**Comment by swentel** [comment]
Given this some more thought, and not going to support this for now, I really don't see a useful use case for this within the app. I even removed the call from Drupal as well for now.
