### ISSUE TITLE
When marking items as read, only apply those to the first page if there are more than the limit

### ISSUE THREAD

**Issue by swentel** [swentel/indigenous-android#150]
This is not that that tricky, we need to send multiple entry ids, instead of marking the complete channel.

Depends on https://github.com/swentel/indieweb/issues/250

**Comment by dshanske** [comment]
Would you consider the traditional options of mark above read and an option to mark/unmark under the menu on each post?

**Comment by swentel** [comment]
Totally. 

I've fixed a partial thing now: when clicking on a channel, it only sends the id's which are on that page. Which means that clicking on 'Load more' will still show 'new' for those entries if they are still unread.

Need to add 'mark unread' to the drupal side first to get the other way around working.

**Comment by swentel** [comment]
done
