### ISSUE TITLE
Can't use syndication targets on Known

### ISSUE THREAD

**Issue by voss** [swentel/indigenous-android#152]
<a href="https://github.com/swentel/indigenous-android/issues" class="u-in-reply-to"></a>I'm using latest indigenous release with Known (0.9.9-a). I have a number of syndication targets setup: github, flickr, mastodon, twitter. I used to be able to syndicate to those, but maybe around 1+ month ago (I don't recall precisely), the checkboxes disappeared, and when I try create a piece of content, I get the following error message in a toast:

![screenshot_20181113-170736](https://user-images.githubusercontent.com/10601/48431231-1e41a100-e769-11e8-9204-8146583afcd6.png)

"Error parsing syndication targets: Value github::access_token at 0 of type java.lang.String cannot be converted to JSONObject"

To check whether it is an issue with the syndication targets, I tried loading up Quill, which shows the syndication targets just fine:

![selection_345](https://user-images.githubusercontent.com/10601/48431245-2699dc00-e769-11e8-905d-d1df2b9c9f31.png)

Can I provide you with any details that can help verify if this is an Indigenous issue, or not?

**Comment by voss** [comment]
Gotcha, I will see if Eddie has a workaround. Thanks!

**Comment by swentel** [comment]
@voss could you try the following:

1. open 'IdnoPlugins/IndiePub/Pages/MicroPub/Endpoint.php'
2. go to line 69

Change:
```
   'syndicate-to' => $account_strings,
```
to

```
  'syndicate-to' => $account_data,
```

I've checked the latest master version, to give you more context where to look:
```
                switch ($query) {
                    case 'config':
                        header('Content-Type: application/json');
                        echo json_encode([
                            'media-endpoint' => \Idno\Core\Idno::site()->config()->url . 'micropub/endpoint',
                            'syndicate-to' => $account_strings,
                        ], JSON_PRETTY_PRINT);
                        break;
                    case 'syndicate-to':
```

The change needs to happen in the 'config' case block, not underneath (Indigenous does not call 'syndicate-to' anymore anyway.

That should fix it. The spec also says it should be an array, so I'd rather see an update in the future in Known instead of having to add code in indigenous for this.

**Comment by voss** [comment]
<a href="https://github.com/swentel/indigenous-android/issues/152" class="u-in-reply-to"></a>That worked @swentel. Thanks a lot!

I'll make an effort to submit a change to core Known for this during the week.

**Comment by swentel** [comment]
ok awesome, I'm going to close this then
Added this issue to the README for people having the same problem.
