### ISSUE TITLE
categories are submitted with invalid category[0], ... names

### ISSUE THREAD

**Issue by sknebel** [swentel/indigenous-android#155]
Indigenous' Micropub requests submit categories (and possibly other values?) as

```
Content-Disposition: form-data; name="category[0]"
```
This format with numbers in [] is not valid for Micropub requests: https://www.w3.org/TR/micropub/#form-encoded-and-multipart-requests says

> For x-www-form-urlencoded and multipart/form-data requests, Micropub supports an extension of the standard URL encoding that includes explicit indicators of multi-valued properties. Specifically, this means in order to send multiple values for a given property, you MUST append square brackets [] to the property name.
> For example, to specify multiple values for the property "category", the request would include category[]=foo&category[]=bar.

**Comment by swentel** [comment]
Fixed in dev. Wlll test with a couple of posts first before pushing a release (most likely tomorrow)

**Comment by sknebel** [comment]
Seems to work correctly in the new release! 🎉
