### ISSUE TITLE
Micropub errors are shown only briefly

### ISSUE THREAD

**Issue by sknebel** [swentel/indigenous-android#156]
Just fixed an issue with my micropub endpoint, but Indigenous only showing error messages for a few seconds made it a bit more difficult. 

I'd suggest either showing them full-screen (although I like that you can just try again, so it should be easy to go back to the post screen) or if you feel that's to "in your face" maybe have an error log section somewhere in the settings where the user can go back and review them?

**Comment by swentel** [comment]
Fair point. Kind of related with #141 where I want to fix error messages in general (some are really too vague), and people aren't unable to figure out what could be wrong in general. My personal preference would be to have an error log section in settings so we can keep the visual error friendly. As an addition, I'd want to try and allow sending a logged error message directly to me, so users don't have to copy/paste long error messages.

**Comment by swentel** [comment]
So, closing in favor of #141 - added a reference there, and some more thoughts.
Going to work on this for the next release.
