### ISSUE TITLE
Uploads via Indigenous Seem to Strip Exif Metadata

### ISSUE THREAD

**Issue by dshanske** [swentel/indigenous-android#157]
**Describe the bug**
If I upload via Quill, I have exif data in the image. If I use Indigenous, I don't. 

**Expected behavior**
Metadata not stripped.

**Additional context**
Assuming its an Android thing.

**Comment by dshanske** [comment]
I believe this is due to the scaling of the image

**Comment by swentel** [comment]
Yes indeed, this is normal when scaling. Kind of related to #126 
Tagging as bug, because it's useful information

**Comment by swentel** [comment]
So closing this in favor of #126
