### ISSUE TITLE
Add a 'compact' mode and full detail activity per post

### ISSUE THREAD

**Issue by swentel** [swentel/indigenous-android#164]
The timeline is sometimes too large imo, making it compact might be more interesting in some cases.

Other things to consider

- Check the look and feel on tablets
- show audio 'inline', so not going to a new activity
- play video 'inline', so not going to a new activity
- play audio 'inline', so not going to a new activity
- Related with #127 - when there's a dedicated activity (single view of items), we don't need to 'fix' the read more. And it gives us more screen estate to print all relevant data.
- It might be handy then to slide from one post to another though, with the context also if the next post is still new or not.
- Better indication of reposts / likes and quotations
- Rework the parsing so videos can work too from feeds, maybe inline. (Check science channel)

**Comment by dshanske** [comment]
What about a full single post view? And a scrolling summary view?

**Comment by swentel** [comment]
running on my phone now, will release in about two weeks or so
