### ISSUE TITLE
 Add PKCE support to IndieAuth

### ISSUE THREAD

**Issue by swentel** [swentel/indigenous-android#166]
Add PKCE support to Indigenous even though IndieAuth servers don't support it yet as a nice progressive enhancement as they add support.

https://oauth.net/2/pkce/
https://chat.indieweb.org/dev/2018-12-10#t1544459279590000
https://github.com/openid/AppAuth-Android

**Comment by dshanske** [comment]
WordPress now has this so you'd have an endpoint to test with

**Comment by swentel** [comment]
done!
