### ISSUE TITLE
Double quotes rendered as HTML entities

### ISSUE THREAD

**Issue by voss** [swentel/indigenous-android#169]
<a href="https://github.com/swentel/indigenous-android/issues" class="u-in-reply-to"></a>I replied to a post through Indigenous, and in my post I had enclosed a couple of words in double quotes. when the entry was posted, the double quotes were turned into HTML entities.

My micropub endpoint is Known 0.9.9-a if that helps.

The example post is here: https://blog.voss.co/2018/excellent-points-i-watched-the-mother-of

**Comment by swentel** [comment]
Interesting. I don't have that on my Drupal installation: looking at the incoming request, it's still a quote at my endpoint, and not an HTML entity. So I suspect that this might be in Known. I assume that when you create a post in Known through the UI, quotes are fine then ?

**Comment by swentel** [comment]
I quickly checked the source code. Looking at IdnoPlugins/Status/templates/default/entity/Status.tpl.php htmlentities is used on the body object, so I think that's ultimately the problem.

**Comment by voss** [comment]
> Interesting. I don't have that on my Drupal installation: looking at the incoming request, it's still a quote at my endpoint, and not an HTML entity. So I suspect that this might be in Known. I assume that when you create a post in Known through the UI, quotes are fine then ?

Indeed, they look just fine when I post in Known.

> I quickly checked the source code. Looking at IdnoPlugins/Status/templates/default/entity/Status.tpl.php htmlentities is used on the body object, so I think that's ultimately the problem.

Again, you are correct (: You can close this one out, as the issue is not with Indigenous.

**Comment by swentel** [comment]
I think using ENT_NOQUOTES should be fine here since < and > will be converted, so no tags are rendered as is. htmlspecialchars is probably even a better option too as that function only converts chars that are relevant in HTML.

**Comment by jgmac1106** [comment]
Yes this a Known issue, The note generator has a builtin rich text editor
and does not accept HTML. I will file an issue.
