### ISSUE TITLE
Indigenous for Android: objects of type string can't be converted to objects from Yarns

### ISSUE THREAD

**Issue by jackjamieson2** [swentel/indigenous-android#172]
See https://github.com/jackjamieson2/yarns-microsub-server/issues/53

Indigenous assumes it should receive an array for  in-reply-to, bookmark-of, repost-of, video and photo, but Yarns returns these as strings.  This is correct, according to the jf2 spec.

**Comment by swentel** [comment]
Ok, parsing errors are solved. will close this one when I push a new release.

@jackjamieson2 if you can check my last comment on the parent issue regarding the double escaping of forward slashes, then I will push right away.

**Comment by jackjamieson2** [comment]
Thanks @swentel - The double escaping is indeed a problem in Yarns. I'll look into this as soon as I can

**Comment by swentel** [comment]
Pushed a new release out!
