### ISSUE TITLE
If Visibility is a property retrieved from q=geo set

### ISSUE THREAD

**Issue by dshanske** [swentel/indigenous-android#186]
**Is your feature request related to a problem? Please describe.**
I want to have my site set the location visibility pulldown on hitting the Find Location Option

**Describe the solution you'd like**
When you query for the name, if there is a visibility property, set the visibility pulldown to this.

**Describe alternatives you've considered**
Doing it on the backend, but then it can't be overridden.

**Additional context**

**Comment by swentel** [comment]
ready for next release
