### ISSUE TITLE
Support profile return in Indieauth flow

### ISSUE THREAD

**Issue by dshanske** [swentel/indigenous-android#198]
https://github.com/indieweb/indieauth/issues/31

As an alternative to parsing the h-card - might need the profile scope, although I'm not a big fan of that.

**Comment by swentel** [comment]
done - looks like the wordpress indieauth endpoint doesn't support token verification yet - see https://indieauth.spec.indieweb.org/#access-token-verification-p-3

It doesn't fail on this when trying to refresh endpoints in indigenous. It does work on the first time.
