### ISSUE TITLE
Geo: start using venues from query

### ISSUE THREAD

**Issue by swentel** [swentel/indigenous-android#207]
After I can get https://github.com/swentel/indieweb/issues/384 in.

**Comment by dshanske** [comment]
Keep me posted on this.. I have not implemented this, but will if I have a client to test with

**Comment by dshanske** [comment]
Keep me posted on this.. I have not implemented this, but will if I have a client to test with.

**Comment by swentel** [comment]
I don't have any default implementation myself, simply because I don't really use it right.
So priority is rather low atm.

**Comment by swentel** [comment]
So I forgot a bit what we're going to do here :) 

If places is available in the response, suggest a list to enter in the location field then instead of using the name property in the geo property?

**Comment by dshanske** [comment]
That would be correct.

**Comment by dshanske** [comment]
I wouldn't mind scoping this out more if you want

**Comment by swentel** [comment]
Oh no, that's fine, I should be able to get something working by tomorrow!

**Comment by dshanske** [comment]
If you do, I have my hack day project for IWC SF

**Comment by swentel** [comment]
It works! This is the object I returned in the response  (the drupal endpoint only supports the geo property by default, so I just hacked something in to test).

```php
$response->places = [
      (object) [
        'label' => 'Place 1',
        'latitude' => '51.123',
        'longitude' => '-0.2323',
        'url' => 'https://example.com/place1'
      ],
      (object) [
        'label' => 'Place 2',
        'latitude' => '51.124',
        'longitude' => '-0.2321',
        'url' => 'https://example.com/place2'
      ],
    ];
```

If venues are found, the location name field will show them as soon as you focus on that input. when you start typing, it filters too in the list. If takes the url if found.

I don't do anything yet with the latitude/longitude of a venue. I was wondering if, when you select a venue, its' coordinates should replace the coordinates that were found by the lookup on the phone. Personally I don't think so, but I don't have strong feelings if otherwise.

I'm going to try and get https://github.com/swentel/indigenous-android/issues/134 in as well tomorrow (my micropub endpoint supports q=contact now) so I can release both on thursday or friday.

**Comment by dshanske** [comment]
Have you considered distance from provided coordinates?

**Comment by swentel** [comment]
> Have you considered distance from provided coordinates?

Not sure what you mean here.

One other thing: should the suggestions also contain the default result that is in the geo property?

**Comment by dshanske** [comment]
In the array for each place, distance from the coordinates in the query. Example, Place 1 is 50 meters from the coordinates, etc. I would say no.

**Comment by swentel** [comment]
oh, that could be interesting indeed. But if you know the distance on the server, you can sort by that already before returning the response, so I think that's good start imo.

I've cleaned up the code a bit and pushed this.
Closing for now, we can always iterate later :)

Will release tomorrow, even if I don't get contacts autocomplete in.
