### ISSUE TITLE
Two-factor authentication causes endless registration loop

### ISSUE THREAD

**Issue by jaranta** [swentel/indigenous-android#210]
**Describe the bug**
Two-factor authentication on the same device as Indigenous requires navigating away from the registration screen while the registration is still unfinished. However, navigating away from Indigenous causes the registration to reset, making it impossible to add new accounts.

**To Reproduce**
1. Try to register a new account that has 2fa enabled.
2. Navigate away from Indigenous to get the 2fa code.
3. Go back to Indigenous.
4. Registration flow has been interrupted.

**Expected behavior**
Indigenous remembers the registration attempt while it is still going on.

**Smartphone (please complete the following information):**
 - Device: Faiphone 2
 - Android version: 7.1.2

**Comment by swentel** [comment]
Oh, very interesting. I know I've had this with some other apps as well. I then put both apps in split screen mode to achieve that, but that's of course totally not ideal (I'm not even sure at which android version is introduced, so probably not even everyone can do that).

I'll look into this soon!

I'll look into this soon.

**Comment by jaranta** [comment]
Apparently mine does: I just found out because of your comment. That will allow me to complete the registration, but I do appreciate you looking into this!

**Comment by kisik21** [comment]
I think it's dependent on device size and manufacturer's wishes, I remember having a device that won't go in split-screen unless you flash AOSP on it...

With password managers not providing reliable autofill it's also a critical issue.

**Comment by swentel** [comment]
I still have not figured out how to fix this. Documented it for now in the README.

**Comment by kisik21** [comment]
Maybe something like saving WebView state in onSaveActivityState? That's how we were taught to preserve state when switching apps or rotating screen...
