### ISSUE TITLE
Add ability to run without Micropub

### ISSUE THREAD

**Issue by jamietanna** [swentel/indigenous-android#219]
**Is your feature request related to a problem? Please describe.**

While trying to log in with my site https://www.jvt.me (https://php.microformats.io/?url=https%3A%2F%2Fwww.jvt.me), I'm getting an error:

```
We did not find the necessary rel links on your domain (authorization_endpoint, token_endpoint, micropub, microsub)
```

I don't have a `micropub` endpoint, so the error is valid, but it'd be great to be able to use the app without needing to have Micropub configuration, as my site's not yet ready for it.

**Describe the solution you'd like**

The ability to use the app without having a Micropub endpoint.

**Describe alternatives you've considered**

Implementing a Micropub endpoint for my site.

**Additional context**

N/A

**Comment by swentel** [comment]
Hey @jamietanna 

I see you have microsub endpoint, so yes, it kind of makes sense that the app would work then :)
For some reason, I decided that you can authenticate without microsub, but not without micropub. Interesting to see that case now!

So, as a quick fix to test the microsub part: if you just add a header link tag with rel="micropub", then you'll be able to authenticate - even if the url is not working, I don't care about that. If at some point you have micropub endpoint which works, you can refresh the endpoints in the app itself in the account section.

**Comment by swentel** [comment]
Micropub is now optional. I'm not exactly sure when a new release will come out as I'm heavily testing at the moment with push notifications. So if you want to test out earlier, feel free to use the trick from my previous comment :)
