### ISSUE TITLE
Implement search or direct filtering of a feed

### ISSUE THREAD

**Issue by swentel** [swentel/indigenous-android#220]
See 

- https://indieweb.org/Microsub-spec#Searching_for_Content
- https://github.com/indieweb/microsub/issues/21
- https://github.com/indieweb/microsub/issues/33

Related with https://github.com/swentel/indieweb/issues/407

Two ideas to implement:

- make the author avatar clickable, then send the author url in the query so that you directly filter on posts from this author in that channel, or use action=timeline&source=sourceID
- search per channel

**Comment by swentel** [comment]
Part one is done. Clicking on the author url (disabled by default), opens the timeline for this source.

**Comment by EdwardHinkle** [comment]
This is really nice! Definitely something I'd like to do on my end

**Comment by swentel** [comment]
And search per channel is in too. Will test for a week before pushing a new release.
Hope we can get an agreement on global search one day!
