### ISSUE TITLE
Handle discovery of endpoints in response header

### ISSUE THREAD

**Issue by swentel** [swentel/indigenous-android#221]
Good example - see https://unicyclic.com/mal/

Fix #147 at the same time too.

**Comment by swentel** [comment]
So I can find the Link endpoints now in the response. However, when testing with unicyclic.com/mal,
I'm arriving at https://unicyclic.com/php/auth_endpoint.php (with additional get params), and the response says 'Error: Please log in first!'. So I'm not sure here what to do. Can I redirect somehow ?

@mblaney any ideas ? Or should I ignore that error. It would mean you'd have to open a browser first, login, and after that, from within indigenous, it should work (as the browser launched from there will probably find the cookie).

**Comment by mblaney** [comment]
Hi @swentel that sounds pretty good, I need to handle that case so that after the user logs in you get the correct data returned.

Feel free to ignore it, but if you want to test further you can create an account on unicyclic.com to get past the logged in check :-)

**Comment by swentel** [comment]
@mblaney new release pushed. After authenticating first in a browser, I can then authenticate with Indigenous. Reader works - although I couldn't see my own feed which I added or maybe I did something wrong, possible too :)

**Comment by mblaney** [comment]
hi @swentel that's great! nice work :-)

what feed were you trying to add? I just logged in as you and tried adding realize.be, which discovered a bunch of feeds that I could add. Let me know if you noticed any errors... or lack of errors after clicking something and it not doing what you expected.

**Comment by swentel** [comment]
@mblaney Hey. So adding the feed worked fine. I saw the items in Indigenous - maybe I was scrolling too fast initially, that's possible :)

However, in Indigenous, you can also manage channels and feeds, and in the 'All' channel, I don't see anything there. Afaik, managing channels works fine with Aperture and the Drupal microsub server. So either Indigenous can't fully parse the 'manage feed in a channel' response from unicyclic (although I should probably see an error I think, should double check), or maybe that's not implemented yet ?

**Comment by mblaney** [comment]
thanks for the feedback, I see the problem now. I use 'all' internally so don't return anything when it's used as a channel name.... will have to fix that!

Also I've been checking to see if indigenous has updated on my phone, and it just did and I can log in :-) will have a play and see what else I need to fix.

**Comment by swentel** [comment]
@mblaney ok cool! If you think there's a problem in indigenous, don't hesitate to open issues :)

It also looks like the 'read' call doesn't get through. The posts are always set to 'new' - note - this is a tricky thing in indigenous (but works with the other two micosub servers).
