### ISSUE TITLE
404 Not Found during Sign In process

### ISSUE THREAD

**Issue by ngm** [swentel/indigenous-android#222]
**Describe the bug**
When signing in, I get a 404 from the redirect to https://indigenous.abode.pub/android/login/ after authorizing the application via IndieAuth on my site.

**To Reproduce**
1. Open the app
2. Add my website address to the field above the 'Sign In' button
3. Click on 'Sign In'
4. Log in to my site, and auth Indigenous
5. Redirected to https://indigenous.abode.pub/android/login/?code=alongcodehere&state=1243-astate
4. See error: 404 No Found (nginx/1.10.3 (Ubuntu))

**Expected behavior**
To be signed in to Indigenous.

**Smartphone (please complete the following information):**
 - Device: Sony Xperia Z1 Compact
 - Android version: 5.1.1

**Additional Context**
- Indigenous 0.34
- I have auth'ed into Indigenous successfully before - but this is the first time I've reauthed in to it for a while, so can't say exactly when it might have started happening
- I'm able to auth successfully with other clients, e.g. Quill

**Comment by swentel** [comment]
Hmm, I switched to a different server for authentication in a later version of indigenous.

This is still on @EdwardHinkle 's server, but it still seems online, so a bit in the dark here.

**Comment by ngm** [comment]
Oops, didn't realise I was so out of date!  I've been getting Indigenous from F-Droid, which is still on 0.34.

I will try the release on Google Play.

**Comment by ngm** [comment]
All working OK in 0.42.

**Comment by swentel** [comment]
Oh yeah, the f-droid build is behind on that, I have an issue open for that catch up soon!

**Comment by tibaultbordeaux** [comment]
Albeit closed here a short note that I'm facing this issue, too. Since I'm on Lineage OS I'm dependent on your builds on f-droid. Thanks anyway for this great piece of software! Keep it up and running. It deserves much more attention in the world out there.

**Comment by swentel** [comment]
@tibaultbordeaux ah, I'm working on a new release for f-droid - also about to switch to Lineage OS full time soon. Created a new issue to push a new one soon with all the latest features - without location or push notifications yet though.

**Comment by tibaultbordeaux** [comment]
@swentel Great to hear - thanks for your fast response!
