### ISSUE TITLE
Share intent: populate title and url when possible

### ISSUE THREAD

**Issue by swentel** [swentel/indigenous-android#223]
If you share a web page, you should get the title and url.
In that case it should be possible to populate the title and url, now I only catch the url

marking as a bug since it's kind of annoying having to manually fill in.

**Comment by dshanske** [comment]
I do this on the backend.

**Comment by dshanske** [comment]
Query might work

**Comment by swentel** [comment]
> I do this on the backend.

Ah yes, that's a good option - I also go and fetch extra information.
It's also possible that some android actions (e.g. share from browser) send extra data, but it doesn't happen always, so closing for now. Not going to bother with a query here.
