### ISSUE TITLE
incorrect request to media endpoint

### ISSUE THREAD

**Issue by sonnyp** [swentel/indigenous-android#231]
> To upload a file to the Media Endpoint, the client sends a multipart/form-data request with one part named file.

https://www.w3.org/TR/micropub/#request

Indigenous sends part name `file[]` instead of `file`.

**Comment by dshanske** [comment]
I had to code a special case for this.

**Comment by swentel** [comment]
Ugh, didn't know it had to be single. Kind of annoying to special case in the code for that, but oh well.

**Comment by swentel** [comment]
ready in dev - will probably release next week.
