### ISSUE TITLE
wrong request on update

### ISSUE THREAD

**Issue by sonnyp** [swentel/indigenous-android#232]
On update, indigenous sends a request with `content-type:  application/x-www-form-urlencoded` and a malformed JSON body (missing root `{` and `}`):

```
content-type application/x-www-form-urlencoded; charset=UTF-8
START BODY:
    action: "update"
    url: "http://192.168.0.3:3000/2019/05/28/17-56-02"
    replace: {
      "content": [
        "Cbxnx"
      ],
      "post-status": [
        "published"
      ]
    }
END BODY

```

**Comment by swentel** [comment]
So i finally double checked on this. I see the root brackets, so a bit confused what is wrong

`{"action":"update","url":"https:\/\/realize.be\/notes\/1899","replace":{"content":["Test update again"],"post-status":["draft"]}}`

I added the right header now though. I'll ping if there's a new release so you can test.

**Comment by swentel** [comment]
There's a new release, not sure if that fixes the original problem though.

**Comment by swentel** [comment]
Tentatively closing.
