### ISSUE TITLE
Link to this repo is not correct

### ISSUE THREAD

**Issue by jamietanna** [swentel/indigenous-android#234]
**Describe the bug**

The link to this repo from within the app has URL escaped some characters which means it does not resolve.

**To Reproduce**
1. Download indigenous 0.43
2. Click on `About`
3. Click on `GitHub` link
4. Notice url is https://github.com/swentel/indigenous%E2%80%93android not https://github.com/swentel/indigenous-android

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Pixel 3a
 - Android version: 9

**Additional context**
Add any other context about the problem here. This may contain strack traces if available

**Comment by swentel** [comment]
Fixed, thanks for the report!
