### ISSUE TITLE
Don't auto submit Share intents

### ISSUE THREAD

**Issue by jamietanna** [swentel/indigenous-android#235]
**Is your feature request related to a problem? Please describe.**

I'd find it quite useful to be able to be browsing on a page, click ie `share to bookmark` and have the sharing intent have the url of the page prepopulated but not autosubmit, so I can add other details to the micropub request. This is frustrating as it means I cannot use the share intents for anything other than likes, as I don't add any metadata to them. 

**Describe the solution you'd like**

The ability to toggle in settings whether the intent auto submits or not. 

**Describe alternatives you've considered**

Enabling it by default for everyone, but that may break the workflow for folks expecting it.

**Additional context**

**Comment by swentel** [comment]
Makes sense. I had an issue at some point where any share intent would basically have both options, but that became a very crowded screen :)

But I'll bring it back, you don't configure this every day I guess.

**Comment by dshanske** [comment]
I would agree. Once you set your preferences, it applies to all sharing.

**Comment by swentel** [comment]
bookmark, reply and repost can now be configured to auto submit or not - defaults to false.
normally there's a new release tomorrow

**Comment by jamietanna** [comment]
Amazing, thank you!

**Comment by swentel** [comment]
new release pushed - should be available in a few minutes I think

It also bumps - internally - to a new api version. Android studio managed to convert a lot of things and everything seems to be working still fine, so crossing fingers :)
