### ISSUE TITLE
Reply contexts on like posts?

### ISSUE THREAD

**Issue by kisik21** [swentel/indigenous-android#236]
**Is your feature request related to a problem? Please describe.**
My like posts show empty, at least in the `?q=source` screen. I suppose it uses the same renderer as the reader.

**Describe the solution you'd like**
Show a little piece of metadata or a full-blown client-side-generated reply context on posts with following properties: `like-of`, `bookmark-of`

**Describe alternatives you've considered**
Adding `p-content` around the post. I'm sure this could be confusing for some readers/parsers.

**Additional context**
n/a

**Comment by swentel** [comment]
Hmm, this is in the overview screen of your own posts right ? That one is indeed a bit boring at the moment, I should really start working on that again - also on my server side as that's not pushing too much at the moment.

**Comment by dshanske** [comment]
What about a server side generated context? There is support in Microsub for extra properties in the reference section

**Comment by kisik21** [comment]
We're talking about Posts screen, which uses Micropub's Post List extension.

**Comment by dshanske** [comment]
Yes, but I was referring to prior art for displaying these in the same way. Should have been more specific

**Comment by swentel** [comment]
> client-side-generated

That's not something I'm going to add, if you mean that Indigenous would crawl for the data, that's just overkill.

If there's more context needed, I want to get it from the response, just like the reader does. If there's a 'refs' property, that could work (the reader uses that). Or add more info on the server side in the content property, that just makes more sense.

The posts screen is also something I don't use that much, just to check which posts I have anyway, I don't want to have the full data there, if I want to see more info, I just go the site :)

**Comment by swentel** [comment]
Going to close this in favor of #132
