### ISSUE TITLE
Manual "endpoint and token" login for testing interaction

### ISSUE THREAD

**Issue by kisik21** [swentel/indigenous-android#237]
**Is your feature request related to a problem? Please describe.**
Allow debug-style login, skipping IndieAuth flow and specifying all data directly. Could help with testing Micropub endpoints in a debugging environment without using the full IndieAuth flow (i.e. external IndieAuth solution used in production)

**Describe the solution you'd like**
A separate button "debug login" somewhere. Opens a new activity, exposing fields for:
 - Micropub URL
 - Microsub URL
 - Access token

**Describe alternatives you've considered**
Developing a debug IndieAuth endpoint set that doesn't authenticate the user and just issues tokens with full scope. Would probably end up being too specific to my project, while this solution is a bit more universal.

**Additional context**
n/a

**Comment by swentel** [comment]
Hmm, I could have probably used that one indeed when developing the app :)

Need to think about this a bit because I'm not sure if it'd be a feature that would be used by many people.

**Comment by swentel** [comment]
Given it some more thoughts. it really isn't a feature that would be used a lot. It wouldn't take that much time, but still. So if anyone wants to code it, I'll happily review it and include it, but for now, closing as won't fix.
