### ISSUE TITLE
Add navigation menu account switching

### ISSUE THREAD

**Issue by dshanske** [swentel/indigenous-android#244]
In the navigation menu, there is an account option.

In many Android apps, the switching in a pulldown of the name. Although Google is switching a lot of their apps to a gesture for this. Suggest removal of the account option, and this be placed in a pulldown under the name along with a settings option to allow for fast switching.

**Comment by swentel** [comment]
Yeah, this is the default template when creating the template with a navigation bar but I removed that in the beginning since I didn't support multiple accounts. I should bring it back indeed.

I would keep the accounts menu item though for full defaults of the accounts and other actions, like add / refresh etc.

**Comment by swentel** [comment]
Working on https://github.com/swentel/indigenous-android/issues/78 now - If I can get that working, I wonder if this is still necessary.

There's stlil the case of having multiple microsub servers. I wonder whether it makes sense to see all channels in the reader. That would make the 'account' part in the drawer completely obsolete in case you have multiple accounts. I can still show it if only once account is used, which is the case in most setups I think.

**Comment by swentel** [comment]
Actually after some thinking, the user in the bar will become the default user when #78 goes in, so switching here still makes sense.

**Comment by swentel** [comment]
Ironically, the more I'm working on #78, where I have a working prototype, the more tricky that one becomes. Drafts, contacts, q=source are also per account .. so I'm thinking that switching is actually more reasonable in the end. and faster too.

**Comment by swentel** [comment]
Moving this to #376 - it's almost done, and awesome!
