### ISSUE TITLE
Move items from one channel to another

### ISSUE THREAD

**Issue by swentel** [swentel/indigenous-android#246]
Or some sort. The idea is that you would be able to move a post to this channel so that it comes in there to read later. Currently I sometimes mark a post as unread, but when new posts arrive, they get marked unread again when I hit the channel (because I automatically mark them unread in Indigenous), so I 'forget' them.

Main question: does this need to be be something that can be stored and retrieved on the microsub endpoint, or should I only keep this in indigenous. The latter means I have to store the complete object in a table somewhere, which should be fairly easy. But I guess an API addition on the microsub spec could work too so that any client can start implementing this. 

Opened an issue in the microsub spec before I start coding something - https://github.com/indieweb/microsub/issues/41

**Comment by jamietanna** [comment]
My workflow for doing this is that I share the post from Indigenous to Wallabag, and then Wallabag is my Read it Later app (largely as it has awesome offline capabilities) but it'd be nice to have inside the Microsub server/client.

**Comment by swentel** [comment]
Switch some thoughts, going to implement moving items from one channel to another, see https://github.com/indieweb/microsub/issues/40

**Comment by swentel** [comment]
Changed the idea: the idea is that you would be able to move individual items from one channel to another.

Currently the 'Mark read' stuff is global, so I will make the configurable per channel. This way people can basically do whatever they want :)

**Comment by swentel** [comment]
First part is done. It's a configurable action in the post menu because not every server supports it ye). Now thinking whether I'd want to have some special setting for a channel to exclude from automatically marking as read for a 'read later' channel

**Comment by swentel** [comment]
Actually, closing for now, this is pretty much what I needed. I can always iterate over things later if needed.

**Comment by swentel** [comment]
Actually added code which allows you to have a 'Read later' channel, it's configurable in the settings. It's hidden if there are no unread posts and marking items as read needs to happen manually.
