### ISSUE TITLE
Dates at midnight have the wrong hour in them

### ISSUE THREAD

**Issue by jamietanna** [swentel/indigenous-android#249]
**Describe the bug**

A date of i.e. `2019-09-29T24:52:00` is being passed to Micropub, which is not a valid date because the 24th hour should be written as 00.

This appears to impact both the date picker and the automagic generated data, as I've seen this issue once for each method of entry.

**To Reproduce**

1. Create a new post
1. Select the date picker
1. Select the publish date to be midnight
1. Observe that the date has an hour field of `24` not `00`

**Expected behavior**

The date should be well-formed and have `00` as the hour field instead of `24.`

**Screenshots**

![Screenshot_20191103-002957](https://user-images.githubusercontent.com/3315059/68082484-52e4b780-fe15-11e9-9247-17db6aecae9c.png)

**Smartphone (please complete the following information):**
- Device: Google Pixel 3A
- Android version: Android 10.0

**Additional context**

N/A

**Comment by swentel** [comment]
Huh, funny, never noticed that as I don't think I've ever posted something on that hour.

Reminds me off #108 as I remember looking at it in the reader dates as well. I vaguely remember reading something in the RFC that '24' is an actual valid hour, however, I fully agree that this is super confusing, so let's just fix this :)

**Comment by swentel** [comment]
So yeah 24 hour format is valid RFC, but it feels awkward. Turns out I was using the wrong placeholders for the 24 hour format notation (kk does 1 -> 24, HH does 0 -> 23). So fixed everywhere now, great! :)
