### ISSUE TITLE
Known Login issue

### ISSUE THREAD

**Issue by zoglesby** [swentel/indigenous-android#25]
When trying to login with my known site I authenticate, grant permission and it returns back to the app login page. I get the validating code message and then an "Authorization failed" message.

I have checked that the auth tokens are being created on the server side. Let me know what I can do to provide you with more information to work on this. 

The domain that I am using in https://zach.oglesby.co and it works with alltogethernow.io and Indigenous iOS.

**Comment by swentel** [comment]
So, Ironically, the "Authentication failed" is used twice in my code so I don't have a clear pointer for myself. I'm going to add more debugging information to the code and roll out a new version as soon as possible, that will make bug reports easier :)

I'll check the https://withknown.com/ project too to figure out if the authentication works different or not (although it shouldn't as far as I know)

**Comment by pstuifzand** [comment]
There is not response_type=code used, I guess.

(Originally published at: https://publog.stuifzandapp.com/posts/529)

**Comment by swentel** [comment]
hmm you're right, that's not set, hopefully it's as simple as that.
Interesting that indieauth.com doesn't complain about that.

**Comment by swentel** [comment]
@zoglesby I pushed a new release, should be available soon.

I added more debug messages to get a clearer view on what might go wrong.
But let's just simply hope that adding the response_type fixed it already, that would be awesome.

**Comment by zoglesby** [comment]
<a href="https://github.com/swentel/indigenous-android/issues/25#issuecomment-380520522" class="u-in-reply-to"></a>The new error is “Value acess_token of Java.lang.String cannot be converted to json_object”

**Comment by swentel** [comment]
Aha, that sounds like the response from the token endpoint is not returning json but probably just plain text. Good pointer! Will digg a bit through the code of Known (or other clients).

**Comment by swentel** [comment]
So it seems the iOS client had trouble with that too and added legacy code. Eddie opened an issue which is now closed but did not fix the issue property afaics.

Will check to add legacy code too easily.

**Comment by swentel** [comment]
@zoglesby So another release, will come up in a few minutes.
Crossing fingers that it will work now, added code that should be able to get the access token from the body in an url encoded string.

**Comment by zoglesby** [comment]
<a href="https://github.com/swentel/indigenous-android/issues/25#issuecomment-380520522" class="u-in-reply-to"></a>That fixed the issue.

**Comment by swentel** [comment]
Awesome!
