### ISSUE TITLE
`h-event`s do not show location / time info in feeds

### ISSUE THREAD

**Issue by jamietanna** [swentel/indigenous-android#252]
**Describe the bug**

When subscribing to a feed that exposes `h-event`s, the detail that is shown is the title and content of the event, but not the event time(s) and location.

**To Reproduce**

1. Create channel in Microsub server
2. Subscribe to https://www.jvt.me/events/homebrew-website-club-nottingham/
4. Notice no times / location

**Expected behavior**
This morning, as for the first time you can subscribe to my feed in Aperture

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Pixel 3A
 - Android version: 10

**Additional context**

This may be a feature request not a bug report!

**Comment by swentel** [comment]
I checked with xray here: https://xray.abode.pub/parse?url=https://www.jvt.me/events/homebrew-website-club-nottingham/ 

So I guess 'start', 'end' and 'location' are the properties to use.

Could you quickly verify with the 'debug' option on the feed or item (see settings, developer options in indigenous) if the feed contains those properties (I guess it will)

**Comment by swentel** [comment]
Testing now - just a note: https://www.jvt.me/events/homebrew-website-club-nottingham/2019/07/24/ crashes with my parser because published is set to 0001-01-01T00:00:00+00:00 - I'll harden this though in the indieweb module at https://github.com/swentel/indieweb/issues/441

**Comment by jamietanna** [comment]
The feed has the following debug for one of the events :

```json
{
    "type": "event",
    "name": "Homebrew Website Club: Nottingham",
    "summary": "Homebrew Website Club on November 13th.",
    "published": "2019-11-05T22:02:22+00:00",
    "start": "2019-11-13T17:30:00+0000",
    "end": "2019-11-13T19:30:00+0000",
    "url": "https:\/\/www.jvt.me\/events\/homebrew-website-club-nottingham\/2019\/11\/13\/",
    "location": [
        "http:\/\/www.ludoraticafe.com\/"
    ],
    "content": {
        "text": "The Homebrew Website Club is a regular meeting for enthusiasts and hobbyist programmers who are building, or thinking of building, their personal websites. The meeting is an informal setting where you can talk with others, get inspiration, or quietly work on your site.\nHomebrew Website Clubs are run across the world and have a mixture of styles for how they operate. In Nottingham we like to have a bit of a relaxed session in the cafe portion of Ludorati. Folks come along for conversations about their websites, building tooling for the Web, to talk about some of the technologies they've been working on, to learn something new, or even just to have a couple of hours dedicated to adding that new bit of functionality or a new blog post.\nWant to RSVP? You can follow the steps in How to RSVP to an Indie Event from your Website."
    },
    "post-type": "event",
    "refs": {
        "http:\/\/www.ludoraticafe.com\/": {
            "type": "card",
            "name": "Ludorati Cafe",
            "url": "http:\/\/www.ludoraticafe.com\/",
            "photo": null
        }
    },
    "_id": "5991472",
    "_source": "2505",
    "_is_read": true
}
```

Ah sorry about that, those posts unfortunately don't have a publish date associated which is why it returns that.

**Comment by jamietanna** [comment]
Interestingly it doesn't contain the full location including address, just the card (which I guess is fine for now if that's all we get back)

**Comment by swentel** [comment]
ok done, looks a like the attached screenshot.

![Screenshot_20191106-115626_Indigenous](https://user-images.githubusercontent.com/168466/68292781-e07e0c80-008c-11ea-9fa6-364562a7a7b3.jpg)

(note: date is one hour later for me as I'm in a different timezone)

**Comment by swentel** [comment]
New release is probably for this weekend. It has a couple of new features (and one crashing bug fix for a feature which is rarely used, so that's fine) which I want to make sure they work fine.

**Comment by jamietanna** [comment]
Amazing thank you 🙌🏼
