### ISSUE TITLE
Cropping pictures before upload

### ISSUE THREAD

**Issue by kisik21** [swentel/indigenous-android#255]
**Is your feature request related to a problem? Please describe.**
Most social network apps I've seen allow to edit and crop a picture before it gets uploaded.

**Describe the solution you'd like**
An additional screen to set the caption and/or edit (draw on, crop, etc.) the picture being uploaded.

**Describe alternatives you've considered**
Using an external program beforehand. Feels clunky.

**Comment by swentel** [comment]
Hmm, I'm not a big fan of this. There are some libraries out there that try to support this, but they are also a bit clunky. I'll have another look at them, but it will come with no warranty at all.

That said, captions (being setting an alt/title text) for a picture is possible by clicking on the picture already.

**Comment by kisik21** [comment]
I know. It seems to transmit the text in "mp-photo-alt" property which is currently unsupported by my Micropub endpoint. I assume that these correspond to photo urls? What happens if a caption is set only, e.g. on first and third pic?

**Comment by swentel** [comment]
Hmmm, good question. It will ignore that, but I'm not sure whether the indexes on the array will follow right. I'll have to check that.

**Comment by swentel** [comment]
So in case you upload 3 pictures, and the second one does not have an alt tag, it will be skipped, so the delta's will not match, so I need to fixed that.

mp-photo-alt is a proposal, see https://indieweb.org/Micropub-brainstorming#Alternative_text_for_photos_in_form-encoded

**Comment by swentel** [comment]
Gave this some more thoughts and I'm not going to add this. There are a couple of libraries out there (https://github.com/burhanrashid52/PhotoEditor seems nice, but no androidx support yet), but I just don't want to support them in case something goes wrong. And I'm not going to start writing this myself either, I simply don't have the resources for that. There are enough apps out there that allow for image manipulation in such ways than I'll ever be able to get close to anyway.
