### ISSUE TITLE
App closes at sign in with "Indigenous has stopped", can't auth

### ISSUE THREAD

**Issue by ngm** [swentel/indigenous-android#258]
**Describe the bug**
When I enter the URL of my site and press SIGN IN, I get the message 'Indigenous has stopped'.  To continue I have to press 'Close app'.  The browser component then loads with my website auth page, and I can log in and auth.   I then get returned back to Indigenous but am on the sign in screen again.

**To Reproduce**
1. Open Indigenous
2. Enter homepage URL
3. Press SIGN IN
4. See error "Indigenous has stopped"
5. Press 'Close app'
6. Auth into website
7. End up back at sign in screen in Indigenous

**Expected behavior**
I should be authed in to Indigenous.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Note 10.1 2014 Edition (SM-P600)
 - Android version: 7.1.2 LineageOS
 - Indigenous: 0.46 from F-Droid

**Additional context**
I'm using the Fennec browser from F-Droid.  (Not the Lineage built-in browser).

**Comment by swentel** [comment]
Good news is that I can reproduce trying to login with your website :)

The interesting part is that It crashes on your site, not mine, so I'll debug further what goes wrong! But I guess it will be something stupid. I'll let you know later this day.

**Comment by swentel** [comment]
So this is a specific 7.1.x android bug - there's even a library to fix crashes on toast messages at https://github.com/PureWriter/ToastCompat (even a simple try/catch in the code doesn't work).

My lineageOS crashes on it as well (yet, not on my site, so I'm trying to figure out the difference).

**Comment by swentel** [comment]
Ok, I've tagged a new release for f-droid. (0.48). This should fix the crash.
Not sure how fast f-droid updates, but let me know if it works, or not too of course :)

**Comment by ngm** [comment]
Great, thanks!  Still 0.47 at the mo - will check again tomorrow.

**Comment by ngm** [comment]
Updated and it's working fine, thanks for much!

**Comment by swentel** [comment]
awesome!
