### ISSUE TITLE
No support for non-SSL in Android 9 or later

### ISSUE THREAD

**Issue by fancypantalons** [swentel/indigenous-android#259]
As documented in this [link](https://developer.android.com/training/articles/security-config#CleartextTrafficPermitted), in Android 9 and later, cleartext traffic is disabled by default (see the note).

I've confirmed the issue by resolving it in a test build using option #2 from [this SO post](https://stackoverflow.com/questions/45940861/android-8-cleartext-http-traffic-not-permitted).

**Comment by swentel** [comment]
Oh lord, how annoying is that!

So basically, this is what you did? (note, I added the tools attribute so the IDE doesn't complain about the fact that the property is only for api level 23 and higher)

```
diff --git a/app/src/main/AndroidManifest.xml b/app/src/main/AndroidManifest.xml
index a41d05a..9c8246a 100644
--- a/app/src/main/AndroidManifest.xml
+++ b/app/src/main/AndroidManifest.xml
@@ -1,5 +1,6 @@
 <?xml version="1.0" encoding="utf-8"?>
 <manifest xmlns:android="http://schemas.android.com/apk/res/android"
+    xmlns:tools="http://schemas.android.com/tools"
     package="com.indieweb.indigenous"
     android:installLocation="internalOnly">
 
@@ -33,7 +34,9 @@
         android:label="@string/app_name"
         android:roundIcon="@mipmap/ic_launcher_round"
         android:supportsRtl="true"
-        android:theme="@style/AppTheme">
+        android:usesCleartextTraffic="true"
+        android:theme="@style/AppTheme"
+        tools:targetApi="m">
```

**Comment by fancypantalons** [comment]
Yup!  With that change the issue is resolved on my end.

**Comment by swentel** [comment]
Ok thanks! Fix committed, thanks for the report, I probably would have never found this one :)

I'm waiting for https://github.com/swentel/indigenous-android/issues/258 to report back positive (that's release 0.48), if it works out, I'll push 0.49 out immediately with this included.

**Comment by fancypantalons** [comment]
Honestly, I had to throw a bunch of additional logging in the code to track it down.

I'll take a look at that area of code when I have some time and think about how perhaps the error handling could be improved to make catching these kinds of issues a little easier.

In this particular case, the app popped the toast with the "Could not connect to domain" error but without the message from the exception there was no way to know why.

In addition, I ran into a problem where my token_endpoint URL was pointing to the wrong place, and while the app reported a 404 when authenticating, there was no way to no *which* phase of authentication failed so I could track down the issue and fix it.

I suspect just a few tweaks here and there would make diagnosing those types of problems a lot easier!

**Comment by swentel** [comment]
> I suspect just a few tweaks here and there would make diagnosing those types of problems a lot easier!

Absolutely. I've been a bit lazy when it comes to better error detection/logging, especially in the authentication part. I'm not 100% happy with the discovery of the endpoints either, I'm hoping to refactor it a bit next year to make it cleaner :)

**Comment by swentel** [comment]
This has been pushed to the android store - and also F-Droid
