### ISSUE TITLE
Parameter client_id is set to the url of the user, but should be the...

### ISSUE THREAD

**Issue by pstuifzand** [swentel/indigenous-android#26]
Parameter client_id is set to the url of the user, but should be the url of the client (Indigenous)

https://github.com/swentel/indigenous-android/blob/5df4116c1532b2bde6b24f1962a48fae9a362db5/app/src/main/java/com/indieweb/indigenous/indieauth/IndieAuth.java#L282

(Originally published at: https://publog.stuifzandapp.com/posts/530)

**Comment by swentel** [comment]
Hmm yes, makes sense. Sign in screen looks nicer now.
Thanks! Will close once a new release is pushed.

**Comment by swentel** [comment]
Pushed in new release.
