### ISSUE TITLE
Validate shared information as url

### ISSUE THREAD

**Issue by dshanske** [swentel/indigenous-android#261]
Some apps share a title and a URL, which Indigenous puts in the url field...It should validate that the shared information is a url.

**Comment by swentel** [comment]
Wow, the app even crashes when you share a url to the note post type - I clearly don't use it as much :)

**Comment by swentel** [comment]
So indeed - when you share a url from a webpage, you also get the title of the page as subject. The url is in the variable I check in the current version.

I can pass on the subject too, but it only seems useful for article as far as I can see. So not exactly sure what action I should take here.

**Comment by dshanske** [comment]
At the least, strip the URL and send only that.

**Comment by swentel** [comment]
I think it's ok now. We can always iterate further. At least the crash is fixed :)
