### ISSUE TITLE
Update https://indigenous.realize.be/ to add IndieAuth client metadata

### ISSUE THREAD

**Issue by jamietanna** [swentel/indigenous-android#262]
As per the [IndieAuth spec](https://indieauth.spec.indieweb.org/#client-information-discovery), it is recommended to provide client metadata marked up as such:

```html
<div class="h-app">
  <img src="/logo.png" class="u-logo">
  <a href="/" class="u-url p-name">Example App</a>
</div>
```

This then allows rendering more information about the client, as seen in i.e. Jacky's post https://v2.jacky.wtf/post/1f8ffba0-e948-4dac-aa6a-3975074cced9:

![2019-12-04-165911_626x147_scrot](https://user-images.githubusercontent.com/3315059/70163450-6a82ba80-16b7-11ea-9cb2-e068525c8f82.png)

(Raised off the back of https://www.jvt.me/mf2/2019/12/qolis/ and https://realize.be/reply/content/1968)

**Comment by swentel** [comment]
Done - mf2 parser is happy - unless I missed something :)

**Comment by jamietanna** [comment]
LGTM, thanks!
