### ISSUE TITLE
I get the error "Error: No value for url" and a white page for...

### ISSUE THREAD

**Issue by pstuifzand** [swentel/indigenous-android#27]
I get the error "Error: No value for url" and a white page for an channel with an item, that has no url. If the url is "required", then only the entry should be skipped and not the whole channel. But perhaps and entry without url, could also be shown?

https://github.com/swentel/indigenous-android/blob/2c4bc92634d4a84dbd7a75b6d31f5c4900612876/app/src/main/java/com/indieweb/indigenous/microsub/timeline/TimelineActivity.java#L158

(Originally published at: https://publog.stuifzandapp.com/posts/531)

**Comment by swentel** [comment]
Oh, I naively assumed that url would also be available.

**Comment by swentel** [comment]
Fixed in code, will close issue when new release is pushed.

**Comment by pstuifzand** [comment]
I guess almost all properties should be seen as optional. I can login, but when I open a channel, I only get "Error: No value for ...", with "url", "name", or "text".

(Originally published at: https://publog.stuifzandapp.com/posts/532)

**Comment by pstuifzand** [comment]
I guess this is what is returned, that will give the error,for "name". I guess it's the case where there is an author, but no info.

```
{
    "type": "",
    "name": "Where we're at with Facebook",
    "published": "2018-04-11T14:04:29Z",
    "updated": "",
    "url": "http://scripting.com/2018/04/11/140429.html",
    "author": [],
    "content": {
        "html": "<p>Here is my summary of what I've been writing on my...</p>\n"
    },
    "checkin": [],
    "_id": "687474703a2f2f736372697074696e672e636f6d2f323031382f30342f31312f3134303432392e68746d6c",
    "_is_read": false
}
```

**Comment by pstuifzand** [comment]
I built my own Microsub server, and perhaps not everything is working correctly yet. As can be seens from the missing "type".

**Comment by swentel** [comment]
Ah, name and url were from author, interesting.
Aperture doesn't send the author key at all when nothing is available (or sends "null" as a string sometimes too in a subkey, no ideal either). But that's fine, code should now work (I hope).

**Comment by swentel** [comment]
Pushed in new release, feel free to reopen if it's still failing (crossing fingers)
