### ISSUE TITLE
Photo uploads are not going via media-endpoint

### ISSUE THREAD

**Issue by jamietanna** [swentel/indigenous-android#279]
**Describe the bug**

When attempting to upload a photo alongside a note, I am receiving a POST request to my `/micropub` endpoint:

```
Content-Disposition: form-data; name=\"h\"\r\n\r\nentry\r\n
Content-Disposition: form-data; name=\"content\"\r\n\r\nG\r\n
Content-Disposition: form-data; name=\"published\"\r\n\r\n2019-12-30T18:07:00+0000\r\n
Content-Disposition: form-data; name=\"post-status\"\r\n\r\npublished\r\n
Content-Disposition: form-data; name=\"mp-photo-alt[]\"\r\n\r\n\r\n
Content-Disposition: form-data; name=\"photo[]\"; filename=\"1577729251403.jpg\"\r\n\r\n����\u0000\u0010JFIF\u0000\
```

However, as per the spec, https://www.w3.org/TR/micropub/#h-uploading-files it should be sent to the media-endpoint first, then referenced as a URL.

**To Reproduce**

Send a request to a server with a media-endpoint defined, and look at the request body.

**Expected behavior**

The upload should go to the media-endpoint, get the URL, then provide that as a parameter on the POST.

**Screenshots**

N/A

**Smartphone (please complete the following information):**
 - Device: Google Pixel 3A
 - Android version: 10

**Additional context**

N/A

**Comment by dshanske** [comment]
I uploaded a photo yesterday and it worked

**Comment by jamietanna** [comment]
@dshanske are you able to see whether the photo was uploaded as part of the multipart request or if it went separately to the media-endpoint?

**Comment by swentel** [comment]
This is the same as #254 
Still low prio because a server must support uploads via POST too, but yeah, if there's a media endpoint it should use that (I hate that part of the spec, but oh well).

**Comment by jamietanna** [comment]
That's a shame, I won't be able to use Indigenous for media uploads until it's resolved. I'll watch #254 in the meantime
