### ISSUE TITLE
Remove GPS tracker

### ISSUE THREAD

**Issue by swentel** [swentel/indigenous-android#282]
Decided to remove the tracker. There are better trackers out there, e.g. http://y20k.org/trackbook/

Together with this, remove the mapbox implementation too, it's way too big anyway.

-- original issue -- 

This is an issue to track bugs and add improvement suggestions for the GPS tracker. 

Things to-do

- bring to F-Droid
- add more fields when posting: content, attachments
- pause/resume track?
- android wear version, so we can more easily track
- see if we can send render the trip on a different external app on the device

**done**

- render points of a trip using Mapbox
- replace atlas single location in timeline with Mapbox
- mapbox telemetry: done in #321 - mapbox is disabled by default

**Comment by licaon-kter** [comment]
What's the Mapbox situation? Will it be disabled in F-Droid flavour?

**Comment by swentel** [comment]
@licaon-kter It will come back, hopefully in the next release. I need to use different services than the one that the playstore version is currently using, basically not using any google service.

**Comment by swentel** [comment]
@licaon-kter pushed a new tag, should be fine now! My comment regarding the tracker is still valid though, but in a microsub timeline, in case there are coordinates, the mapbox should work now, if the build works now of course .. :)

**Comment by licaon-kter** [comment]
You can always just show a button and whatever app the user has (eg. OSMAnd) will open the `geo:`, right?

**Comment by swentel** [comment]
@licaon-kter hmm, that makes sense, I'll make mapbox optional for the timeline part!

**Comment by licaon-kter** [comment]
Some more thoughts:
* users might not trust Mapbox (iirc it shares data with 3-rd party), eg. see this long discussion https://gitlab.com/fdroid/fdroiddata/issues/1611 
* maybe you'd end up with [AntiFeatures](https://f-droid.org/en/docs/Build_Metadata_Reference/#AntiFeatures) added to your app on F-Droid if the map functions are not opt-in (so users know that by enabling they send their location to Mapbox & friends)
* not sure what Mapbox's policy for publicly sharing the key

**Comment by swentel** [comment]
Good points, thanks for the feedback!

- MapBox has a feature to turn the default sharing off programmatically, will implement that in the next version, together with the opt-in of mapbox.
- Regarding the public key, I /think/ that's fine, but I will double check with them. It's the default 'public' key listed in my account. It's also used for the web integration I use on my site. I would hope that, at least on the android side, a key would be locked to the package name and if suddenly another call would come in, it would be blocked at their side :)

**Comment by licaon-kter** [comment]
I can compile any app with any package name I wish, not sure that's useful :))

Yes, I can't publish it on Play or F-Droid...but I can distribute the APK

**Comment by swentel** [comment]
@licaon-kter hehe true. Unless I'm wrong, I see you have access to f-droid, so I guess you know how it more or less works, is it possible for me to alter the build process so that it takes keys from a secure place then for instance?

**Comment by licaon-kter** [comment]
No secrets, everything needs to be open-source so that anyone can build the app, and yield the same results.

I've brought the key discussion up because of the points above so you'd know, if the need arises, how to proceed and have things in order, Mapbox still working and the app available in F-Droid.

**Comment by licaon-kter** [comment]
0.57 builds ok

**Comment by swentel** [comment]
Ok, thanks for all the feedback and suggestions so far, much appreciated :)

I'll ping you when I made the mapbox stuff opt-in, with some luck over the weekend if all goes well!

**Comment by swentel** [comment]
Just committed #321 - mapbox is now disabled by default. The map icon in the reader triggers an intent to open a map application on the device which will receive the coordinates. Sending multiple points used in the tracker is way more tricky, so the map icon is disabled completely there if the mapbox setting is not enabled for now. Added a information about the telemetry used by Mapbox and how you can disable it the first time a mapbox map is loaded.

As for the keys: I can manage the tokens (created and revoke) on my account, so I will simply rotate them now and then, or unless I see something weird in the reporting on my account.

New release probably for the weekend, want to get a couple of other things as well.

**Comment by swentel** [comment]
Decided to remove the tracker. There are better trackers out there, e.g. http://y20k.org/trackbook/ 
Together with that I will remove the mapbox implementation, it makes more sense.
