### ISSUE TITLE
Error "We ran into an exception getting the accounts"

### ISSUE THREAD

**Issue by bekoli** [swentel/indigenous-android#306]
**Describe the bug**
Clicking on 'Accounts' throws exception:

"We ran into an exception getting the accounts. Please manage the accounts from the accounts section."

**To Reproduce**
1. Go to 'Accounts'
2. See error

**Expected behavior**
See account management form.

**Screenshots**
![image](https://user-images.githubusercontent.com/5016428/73726666-3caa0880-4730-11ea-99b2-3f0ee4733e7e.png)

**Smartphone (please complete the following information):**
 - Device: KIW-L21
 - Android version: 5.1.1
 - Indigenous version: 0.54

**Additional context**
Works fine otherwhise. It's still connected to my Micropub/Microsub endpoint and I can read/post just fine.

It has been like this since I first installed it but it did usually crash completly when clicking on `Accounts`. Getting an exception and a chance to recover is new.

This screenshot is from _Android_ => Settings => Accounts => Indigenous

![image](https://user-images.githubusercontent.com/5016428/73727087-1cc71480-4731-11ea-9763-abaae876eb52.png)

I get options `Sync` | `Delete` here. That's all.

**Comment by swentel** [comment]
Yeah, I still don't know exactly how to fix this for all Android version. Before a certain version, an explicit permission check should work, but apparently it doesn't :)

Will have to see if I can spin up an old Android version in studio, fingers crossed :)

**Comment by swentel** [comment]
Ok, I was able to spin one up and had no problems getting to that screen.

I see these permissions in the app settings (so the implicit check works at least)

![Screenshot from 2020-02-06 09-11-12](https://user-images.githubusercontent.com/168466/73917882-a822e000-48c0-11ea-8e3f-0138f349d1d1.png)

If you see those as well, then I have no idea to be honest why that error is popping up :/

**Comment by bekoli** [comment]
Same permissions here. I'll try removing and recreate the profile. Mayhap something in the profile or filesystem is broken.

**Comment by swentel** [comment]
So I committed something which /might/ fix it. Will push a new release normally this weekend!

**Comment by bekoli** [comment]
Deleted and recreated account. Same error :(

**Comment by bekoli** [comment]
Nice, will waot for the release to roll in and test again :+1:

**Comment by bekoli** [comment]
Fixed in 0.56 🎉👍
