### ISSUE TITLE
Add better way to add tags to a post

### ISSUE THREAD

**Issue by swentel** [swentel/indigenous-android#33]
Not ideal at the moment. Would be nice if we can have a list of 'popular' tags in a list.

**Comment by dshanske** [comment]
The WordPress Micropub server supports q=category to retrieve all tags. Would you consider supporting this for tag autofill?

**Comment by swentel** [comment]
Oh sure, didn't know that query existed, makes sense.

**Comment by dshanske** [comment]
I think I am the only one who implemented it so far

**Comment by swentel** [comment]
Question, can the response be cached, or should it always get the tags fresh from the server every time you're on the Note screen?

**Comment by dshanske** [comment]
My thought is a cache set to daily and some way to force a refresh. It's an opinion though

**Comment by swentel** [comment]
This is in. It's a setting which you need to enable so that there aren't needless requests to a non existing endpoint. The tags are always fetched live, but cached so the autocomplete also works when working in offline mode. The widget is standard autocomplete widget, might make it more fancier in the future, but for now this works fine for me :)
