### ISSUE TITLE
404 received when using Unread Items

### ISSUE THREAD

**Issue by jamietanna** [swentel/indigenous-android#339]
**Describe the bug**

Attempting to view Unread Items fails with a 404: `channel not found` error.

**To Reproduce**

1. Click `Unread Items`
2. Notice error

**Expected behavior**

Unread items are displayed

**Screenshots**

N/A

**Smartphone (please complete the following information):**
 - Device: Pixel 3A
 - Android version: 10

**Additional context**

My MicroSub reader is https://aperture.p3k.io/

I've been seeing this issue since the feature was first implemented, but I haven't raised it until now - sorry!

**Comment by swentel** [comment]
This isn't supported by aperture, IIRC. This feature is describe in https://github.com/indieweb/microsub/issues/37 , which was a spin off from https://github.com/indieweb/microsub/issues/24

**Comment by swentel** [comment]
So unless I'm wrong, this can be closed.
