### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by grantcodes** [swentel/indigenous-android#346]
Would be great to have an automatic dark mode theme.

I don't know too much about it but there is an option built into newer versions of android that apps can read and choose to use a dark theme.

**Comment by swentel** [comment]
Looks easy when reading https://developer.android.com/guide/topics/ui/look-and-feel/darktheme

Will test soon.

**Comment by swentel** [comment]
Did a quick test, and defaults are fairly ok.
But it's simple to define, just need to find sensible colors for that mode :)

![indigenous-default-dark](https://user-images.githubusercontent.com/168466/77827666-49871f00-7117-11ea-9915-84d300008d79.png)

**Comment by swentel** [comment]
So it really does turn out to be easy, but choosing colors is the tricky part.
Here are some shots, I kind of like them, what do you think? We can always iterate over them once I push this in a release - I can't test on a physical device either, my phone doesn't support it yet, so I only see it in the emulator

![Screenshot_1585433811](https://user-images.githubusercontent.com/168466/77835161-7e609980-714a-11ea-9f19-1b4dc6b65f15.png)
![Screenshot_1585433714](https://user-images.githubusercontent.com/168466/77835163-7ef93000-714a-11ea-873f-9c2bafe2a914.png)
![Screenshot_1585433709](https://user-images.githubusercontent.com/168466/77835166-7f91c680-714a-11ea-8903-4bc36dce9609.png)
![Screenshot_1585433692](https://user-images.githubusercontent.com/168466/77835167-802a5d00-714a-11ea-8f77-4cc72abdf8aa.png)
![Screenshot_1585433688](https://user-images.githubusercontent.com/168466/77835169-80c2f380-714a-11ea-8f4a-962ada685350.png)

**Comment by swentel** [comment]
I actually can enable dark mode on my device programmatically. Going to add a switch in settings to allow setting it to the dark theme.

**Comment by dshanske** [comment]
I would say you should have  a setting, Enable, Disable/Use System Settings.

**Comment by swentel** [comment]
Yep, just add that to the settings

![night](https://user-images.githubusercontent.com/168466/77835864-57599600-7151-11ea-96ae-8485cc39034d.png)

**Comment by swentel** [comment]
Ok committed this. For some reason, I can't get it working for creating a new account when it's enabled via setting - but it works when dark mode is set globally.

We can always iterate on the colors later if necessary, but I personally like it.
Now on to 'Mark read when scrolling', so with some luck, a new release today!
