### ISSUE TITLE
Dark mode contrast isn't the most readable

### ISSUE THREAD

**Issue by jamietanna** [swentel/indigenous-android#349]
**Describe the bug**

The contrast between text and the background isn't the most readable, and likely will make it difficult for those with sight impairments - it may be good if we can adjust this.

**To Reproduce**
1. Use dark mode
2. Share content to Indigenous

**Expected behavior**

Contrast provides bolder difference between text and background.

**Screenshots**
![](https://media.jvt.me/ujtcq.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 3A
 - Android version: 10

**Additional context**
N/A

**Comment by swentel** [comment]
Added better contrast of the action buttons, both in timeline and share screen

Way much better if I say so myself :)

Note sure exactly when I'll push a new release, not many changes so far.

![Screenshot_20200410-234547_Indigenous](https://user-images.githubusercontent.com/168466/79025288-9b06c380-7b85-11ea-8e8c-c43f82b7eec8.jpg)

![Screenshot_20200410-231755_Indigenous](https://user-images.githubusercontent.com/168466/79024110-3dbd4300-7b82-11ea-8360-ad83792cd6f6.jpg)
