### ISSUE TITLE
Pull more data for likes and bookmarks

### ISSUE THREAD

**Issue by smaffulli** [swentel/indigenous-android#370]
As a user, I'd love the app to populate the title of the URL I'm liking or bookmarking so I don't have to type on mobile.

For example, when I Like or Bookmark a URL from my phone, the default post looks like this:

![image](https://user-images.githubusercontent.com/1348736/82741832-a89f9380-9d56-11ea-9312-a2feaac58298.png)

and the anchor has an empty text:

![image](https://user-images.githubusercontent.com/1348736/82741838-c1a84480-9d56-11ea-9dbc-5c8cc67a2810.png)

```<a href="Coronavirus in N.Y. Live Updates: Gatherings of Up to 10 People Allowed https://nyti.ms/3bYgvp6" class="p-name u-url">  </a>```

The Bookmark type has similar issues:
```<a href="Coronavirus in N.Y. Live Updates: Gatherings of Up to 10 People Allowed https://nyti.ms/3bYgvp6" class="p-name u-url">  </a>```

**Comment by swentel** [comment]
I'll do another effort, tried it a couple of times but got stuck on weird things :)

**Comment by dshanske** [comment]
@swentel I do this on the backend. Micropub query?

**Comment by swentel** [comment]
@dshanske well, I actually see that data coming in, so I think I should be able to fix it.

**Comment by swentel** [comment]
So I've been wondering, there's no title field for the like in indigenous. Does it make sense to expose that, or isn't that something that should happen on the server ? @dshanske I think @smaffulli uses wordpress, so I assume this is something that should rather be handles on the server for the like part?

(that said, I'm still looking for EXTRA_TITLE though)

**Comment by swentel** [comment]
Also, I just noticed the actual problem on the screenshot, and a bit confused: @smaffulli are you adding the text in the single url field on indigenous? I'm simply wondering how it gets posted? Because as far as I know, I only populate the url now.

**Comment by smaffulli** [comment]
@swentel I made a screencast of the flow of a bookmark from Indigenous to WordPress. This is what happens on my screen: https://photos.app.goo.gl/CoZ9ZCJSqTSsNG7W8
I did a lot of other tests and I believe the behavior depends on the page being bookmarked... or it's the WordPress backend that is sometimes doing magic, failing other times... I know too little to make any guess.

See the examples I left on my blog to debug 
https://maffulli.net/2020/06/02/6346/
https://maffulli.net/2020/06/02/6345/
https://maffulli.net/2020/06/02/6343/
https://maffulli.net/2020/06/02/6341/

**Comment by swentel** [comment]
Interesting. @dshanske Is it possible there's a bug in wordpress templates then somehow?

@smaffulli I'm working to prefill the title in bookmarks too now. As far as representation goes, that's tricky since the app has no idea what backend is used. For instance, I use Drupal, someone else might use a static site, so I don't know how things look on anyone's site :)

**Comment by swentel** [comment]
ok, as you see in the first screenshot, the title is in the href, which is kind of weird :) (not sure who does that though)

**Comment by swentel** [comment]
More data is pulled in. Will be testing this a few days, a new release should be there in a week or so.
