### ISSUE TITLE
Are the RSVP and Open Link buttons the wrong way around?

### ISSUE THREAD

**Issue by jamietanna** [swentel/indigenous-android#375]
**Describe the bug**

When viewing events in the feed, the actions Indigenous presents (such as like/RSVP) don't look in the right order.

**To Reproduce**

View a feed that contains events, i.e. https://events.indieweb.org/

**Expected behavior**

I would expect RSVP to be grouped with other actions (such as like)

**Screenshots**
<img src="https://media.jvt.me/cf97b1db5d.png" alt="A screenshot of Indigenous for Android, where the RSVP button is after the Open Link" />

**Smartphone (please complete the following information):**
 - Device: Pixel 3A
 - Android version: 10

**Additional context**

N/A

**Comment by swentel** [comment]
Hmm, I guess it makes sense indeed to move the external link button to the outer right, will switch that.

**Comment by swentel** [comment]
Moved to responses section
