### ISSUE TITLE
Refactor IndieWeb components into a Library

### ISSUE THREAD

**Issue by jalcine** [swentel/indigenous-android#379]
**Is your feature request related to a problem? Please describe.**
I'm interested (and mentioned before) an interest in having the core IndieWeb facets of this project (IndieAuth, Microsub, Micropub et al) made into a library so we can use it in other projects.

**Describe the solution you'd like**
A inline library (or maybe separate project? It seems like in-lining the library might be easier for development but harder for releasing) that implements / represents each of those specifications. This might highlight the need to have a Microformats library for Android/Java but we'll get to that when we get there.

**Describe alternatives you've considered**
The first thing I wanted to do was build this up from scratch and propose it for use. That was obviously a bad idea especially since so much work has been put into this project already. I'll work on the librarization of some stuff in my fork of the project and try to keep it upstream patches small.

**Additional context**
This is coming with an agenda. I want to work on making a NativeScript library that wraps this library and the iOS library for IndieWebKit so I can smoothly implement applications for both environments without having to worry too much about parity.

**Comment by swentel** [comment]
Sounds good to me. FWIW, I'm planning to add new 'account types' to Indigenous very soon (starting in July): connect to pixelfed, mastodon, {insert favorite service here). That means quite some refactoring for every part in the chain: authentication, posting and reading.  I have some ideas for that already, which should make extracting the IndieWeb parts (relatively) easy. 

I personally prefer extracting them to a separate library, Indigenous would simply add it to the gradle build. That means a bit more coordination with releases, but I think that's still the best way to go ultimately. And, as you mention, these projects should be Android agnostic.

Regarding mf2: there's https://github.com/kylewm/mf2j - I run a modified version of it in Indigenous, but I haven't actually pushed the changes into https://github.com/swentel/mf2j.

As to where those projects should live: maybe we can start adding them to the IndieWeb project here on GitHub? Not sure who owns that account and if it's possible to limit projects to maintainers (but I guess it is), but it seems the most logical step forward. I guess that we would be the owners in the very beginning, but if at some point we don't like maintaining it anymore, someone else can step in easily :)

Projects I currently see: 

- IndieAuth
- Micropub 
- Microsub
- Contacts (followers/followees)
- Mf2

I'll ping again here as soon as the first account type is in Indigenous, with some luck mid july!

**Comment by swentel** [comment]
New release pushed!

There's more abstraction - although it still could be better of course, but that's software.

Closing this, I'm not going to work actively on this myself, but I'm certainly willing to accept pull requests for further cleanups and abstractions - Also I like to keep my clean queue :)
