### ISSUE TITLE
Add background service that polls for new items even when the app is sleeping

### ISSUE THREAD

**Issue by swentel** [swentel/indigenous-android#38]

**Comment by swentel** [comment]
So while this is quite cool, Eddie is experimenting with push notifications, which are more interesting, especially when there are replies (or any type you want to be notifified for basically).

background services are battery draining, so let's keep this as is for now.

**Comment by swentel** [comment]
Actually, it's clear that I need this, let's do this!

**Comment by dshanske** [comment]
You can set it to poll on a schedule, poll only when on wifi, etc.

**Comment by swentel** [comment]
There's now a setting to poll every hour if the device is awake. There's also an option to only check the 'notifications' channel before sending a notification to the phone itself.

Testing this a bit for a couple of days now, will see how it behaves.
