### ISSUE TITLE
Error 403 - Can't read configuration, can't read subscriptions (WP only) 

### ISSUE THREAD

**Issue by rikmendes** [swentel/indigenous-android#396]
**Describe the bug**
Since the last update I lost all my accounts inside the app
I had a Known & WP account, I noticed a 403 on my already authenticated WP
So I thought let's disconnect it, maybe tokens need to be refreshed, so I disconnected the WP instance
and just like that lost all my other accounts (2 WP and one 1 Know) 

The app reverted to the Anonymous user and when I tried to re-add my WP instance I see shortly a 403 error that slips away and I have no idea how to collect more logs or something to help debug this out. 

**To Reproduce**
1. Switched account & noticed 403 error
2. removed the WP account and all the accounts disappeared
3. Can't add new accounts now, each time I re-add my account I'm back to the Anonymous user reading list

**Expected behavior**
I expected that by removing/adding the same account I would not love my other accounts inside the app. 
Before removing I tried to refresh the connection to the endpoints but that also would create a 403 error popup.

**Screenshots**
x

**Smartphone (please complete the following information):**
 - Device: Huawei P20 Lite ANE-LX1
 - Android version: 9
**Additional context**
x

**Comment by swentel** [comment]
Hmm crap. Quick question, when you add a new account, do you see the account in the Android account section (so not the accounts section in Indigenous) ?

If so, then there should be a 'select account' button in Indigenous when you go to the 'Add account' screen like the screenshot underneath. 

![select-acount-button](https://user-images.githubusercontent.com/168466/89406975-497ad980-d71e-11ea-8ebc-86b06252bfbe.png)


If that isn't there, could you try the following:

- clear all data from the app - depends a bit per android version where this is, but there should be an apps overview somewhere, where you can click on the detail and you can clear cache and data. Wipe everything.
- reconnect again

In case that works, I at least have a clue how to get the select accounts button back - but not sure yet why you got the 403 initially.

**Comment by rikmendes** [comment]
Oh Sorry Yes I forgot to say this, I can see the new multi protocols interface, in fact I tried to add my pixelfed instance, I would simply go back to the reader screen without the account being added in the account list, same for mastodon and indieweb. 
I can see up to when I log in to my own wp site, pixelfed instance or mastodon instance, I authorize etc..all that part seems to behave as it should, it's when the callback happens, when I'm supposed to be sent back to the app and see my accounts added and choose the default one, that's the part that broke it seems :/

**Comment by swentel** [comment]
Hmm I need to be sure about something:

1. You do not see the 'Select account' button?
2. Did you try wiping all app data (reinstall probably also does the same, although I'm not 100% sure of that)

**Comment by rikmendes** [comment]
Wow even more strange things happening, so I cleared the cache & data from the app. 
- Opened the app and I see this new switching icon in the right top pane of the app
- I can see ALL the accounts I added, even my rmendes.net website twice, I see the WP instance I thought to have lost
and I see the mastodon account I added earlier (twice) 
![Screenshot_20200805_135051_com indieweb indigenous](https://user-images.githubusercontent.com/12155003/89411136-34557900-d725-11ea-87f1-1e3fa1f0b342.jpg)

- when I switch from one account to the other I don't see the 403 popup anymore but when I refresh an already connected account (wp instance with Yarn micropub) I see : Error getting configuration, status code: 403; message: {"c...
That's the same error I was seeing earlier. 
![Screenshot_20200805_135205_com indieweb indigenous](https://user-images.githubusercontent.com/12155003
I tried to refresh the status of my second WP instance and boum, repeat of the bug : 
all accounts are gone, I'm back to the anonymous settings view : 
![Screenshot_20200805_135022_com indieweb indigenous](https://user-images.githubusercontent.com/12155003/89411109-29024d80-d725-11ea-8ab8-b74fa3a01007.jpg)


but my accounts seems to still be there if using the new account switcher icon : 
![Screenshot_20200805_135051_com indieweb indigenous](https://user-images.githubusercontent.com/12155003/89411212-55b66500-d725-11ea-9177-f1ce5f3c394a.jpg)


Also it seems the app see a pixelfed account as a mastodon account. When I select it to post something I can see (mastodon) on top, when it should be Pixelfed and the publishing view also show the exact same layout, even with the sensitive and warning mentions that seem to belong to mastodon type of posts ?
![Screenshot_20200805_135148_com indieweb indigenous](https://user-images.githubusercontent.com/12155003/89411232-5fd86380-d725-11ea-8d79-ead187224c5e.jpg)

**Comment by rikmendes** [comment]
Sorry if it's a bit confusing, but In short, after testing posting or reading, it seems the issue is only with Wordpress + Yarn Micropub/sub + Indieweb, because Known or Pixel/Mastodon don't suffer from any issue on the client app.

**Comment by swentel** [comment]
No problem, I'm able to follow so far :)

It's interesting that the pixel account thinks it's mastodon. I don't have that problem on my phone, but I have a bit of a guess. But that's the least of the problem (ironically, most things will/should work because the API is more or less the same for both)

The WP thing is quite interesting - and weird in a way. I'll have to test with my local machine and click on the sync button to see what happens. I hope I can reproduce this problem myself.

Sorry for the problems, I thought I had this upgrade covered, but alas, I guess that's software :)

I'll get back as soon as possible!

**Comment by swentel** [comment]
Regarding mastodon which should pixel. You'll have to delete that account and reconnect again, it isn't possible to switch the internal account type (yet), it will indeed show properties from Mastodon which aren't available (yet) with Pixelfed.

Still thinking about the WP/Yarns problem. Could you show me a screenshot of the accounts section on the phone itself? So not indigenous, but somewhere at 'Settings' -> 'Accounts'

**Comment by rikmendes** [comment]
Regarding the Pixel account showing up as Mastodon account : its just a detail, low importance, that part is functional, that's the most important!

Regarding Yarn/WP
Here is screenshots of the settings/account view on my android
![Screenshot_20200805_154253_com.android.settings.jpg](https://user-images.githubusercontent.com/12155003/89420706-666dd780-d733-11ea-81b1-aa7e780c1051.jpg)

By the way the two mastodon like instances above have their own "Mastodon" label with Indifenous icon ![Screenshot_20200805_154236_com.android.settings.jpg](https://user-images.githubusercontent.com/12155003/89420800-83a2a600-d733-11ea-8a58-b1f827a5c15c.jpg)

And it show up like this
![Screenshot_20200805_154302_com.android.settings.jpg](https://user-images.githubusercontent.com/12155003/89420827-8ac9b400-d733-11ea-9963-817e718f3829.jpg)

I tried to sync from there, I couldn't say if it worked or not since I have no visual clue that a sync took place and no errors..

**Comment by dshanske** [comment]
With WordPress IndieAuth, tracking an issue introduced in 3.5 that affects some users.

**Comment by swentel** [comment]
@rikmendes syncing on those account doesn't do anything (yet) - not sure if I'll ever get anything working there, but can't disable it either.

Secretly hoping that the problem with WP/yarns is related with what @dshanske writes - is there an open issue for it, I'll update my local wp installation to see if I can reproduce the problem as well.

**Comment by rikmendes** [comment]
> With WordPress IndieAuth, tracking an issue introduced in 3.5 that affects some users. 

I noticed now, my WordPress instance auto upgraded this plug-in sometimes this morning, thanks for the heads-up, I will downgrade to my backup and see from there :)

**Comment by rikmendes** [comment]
Adapted the title to better suite what's going on.

Accounts get created just fine, maybe it's just the screen view after the account is created that confused me.. 

It should bring me back to the list of accounts to choose the default one if many accounts connected and simply show the single account being default?

**Comment by swentel** [comment]
> Accounts get created just fine, maybe it's just the screen view after the account is created that confused me..

Yeah, I agree the UI/UX isn't optimal here indeed. The default account is only set when there are no accounts at all. As soon as you have at least, the current user stays the default.

There's a case to be made for both variations: switch or keep the current user. Not sure exactly yet what the best option is :)
What if there's a checkbox which you can toggle which says something like 'Set default after succesfull authentication' ?

**Comment by swentel** [comment]
To anser my own question, here's a checkbox on the authentication screen.

![set-as-default](https://user-images.githubusercontent.com/168466/89452088-6a165400-d75d-11ea-95d0-378f91a62ec7.png)

**Comment by swentel** [comment]
I've updated my local install to 3.5.0 of IndieAuth but not experiencing any errors with connection, or syncing. So a bit in the dark what goes wrong on your end at the moment.

**Comment by swentel** [comment]
BTW - just noticed you are adding french translations, thank you already for that! :)

**Comment by swentel** [comment]
This is just a wild guess and maybe not relevant as I don't see anything special between 3.4.2 and 3.5.0, but you never know: is it possible that this might be related with the 'Set User to Represent Site URL' setting on wp-admin/admin.php?page=indieauth ?

Maybe set an explicit user there if nothing is set and see if that fixes the 403 errors?

**Comment by rikmendes** [comment]
> This is just a wild guess and maybe not relevant as I don't see anything special between 3.4.2 and 3.5.0, but you never know: is it possible that this might be related with the 'Set User to Represent Site URL' setting on wp-admin/admin.php?page=indieauth ?
> 
> Maybe set an explicit user there if nothing is set and see if that fixes the 403 errors?

I verified and I had it already set as my only user, but just to make sure I tried with & without that main user and I have the same 403 error reading configuration etc...

**Comment by swentel** [comment]
Ok, good the know. Looking at the code of IndieAuth/Yarns it seems to be an issue with not finding the access token or (possibly) not having the right scope ('read') .. but I assume that scope has been accepted on authorization.

I'm starting to wonder: would you allow me to quickly try and connect with your site? I can look at the outgoing requests in my debugger to see what's going out, and also the exact response. If you change the password temporarily to something else, then I  make the auth. I'm not sure if you're on IRC, otherwise, feel free to ping me there.

Of course, no problem if you're not in for that :)

**Comment by rikmendes** [comment]
I was going to allow you & checked my setup one last time, when I refreshed the existing account inside Indigenous, I saw successfull reading of the configuration endpoint, I can now see the blogs I'm subscribed too..

I have to specify : I didn't reverted back to my previous WP backup

In fact I didn't changed anything on my side and it seems everything is fully operational now.

I have no idea what happened :/

**Comment by rikmendes** [comment]
I'm going to test with my second WP instance, this doesn't make sense

**Comment by swentel** [comment]
Funky indeed :) Crossing fingers the second WP instance works too. In case there are problems then, let me know the two url's, especially if one is on a subdomain for instance, that might be clue - but still crossing fingers though :)

**Comment by rikmendes** [comment]
> Funky indeed :) Crossing fingers the second WP instance works too. In case there are problems then, let me know the two url's, especially if one is on a subdomain for instance, that might be clue - but still crossing fingers though :)

both are naked domains hosting WP directly. I'm still catching up on testing on my second WP, will report back !

**Comment by swentel** [comment]
Pushed a new release with some of the ux fixes.

**Comment by swentel** [comment]
Haven't heard about any issues from other users so far, closing for now.

In case you still have troubles, or specific steps to reproduce, let me know for sure! :)

**Comment by dshanske** [comment]
@rikmendes Do you have Jetpack installed?

**Comment by janboddez** [comment]
Wondering if the conversation over at https://mastodon.social/@pauho/104865523476413630 is related to this issue, too.

I also noticed that if I remove my default account (or add a new one to an otherwise brand-new install, but "forget" to tick the "default" checkbox, I'm still faced with the anonymous account's feeds, despite being signed in OK. And that the process for subsequently making an account the default one is rather unclear.

Heading over to Accounts, I mostly just see information about the anonymous account, and have to actually click the "Add account" icon in the top right corner get to a screen with a "Set default account" button (below the various "new account icons"). Only then am I able to bring up a dialog that lets me select a previously added account.

**Comment by janboddez** [comment]
Maybe if for whatever reason there's only one account ('cause it's the first one, or because all other accounts got purposely deleted), it should always be set as default?

**Comment by swentel** [comment]
> Maybe if for whatever reason there's only one account ('cause it's the first one, or because all other accounts got purposely deleted), it should always be set as default?

That should be the case, but I will definitely double check!

**Comment by janboddez** [comment]
Yeah, I just checked and if I delete my default account, I instead get to see the anonymous feeds/account, although my other account is still there (and working okay). I have to manually set it as the default one.

**Comment by swentel** [comment]
Interesting, split off in separate issue for it at https://github.com/swentel/indigenous-android/issues/406
Thanks for the feedback already!
