### ISSUE TITLE
Alt tags are not being sent via Micropub requests

### ISSUE THREAD

**Issue by jamietanna** [swentel/indigenous-android#401]
**Describe the bug**

When uploading a photo via Micropub, the `photo[]`'s are missing the `mp-alt[]`.

**To Reproduce**

1. Create a note, with a body of `content`
2. Attach a photo
3. Set the caption to `something`
4. Send request
5. On Micropub endpoint, see that no alt tags are sent

**Expected behavior**

Alt tags should be sent

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Google Pixel 3A
 - Android version: 10

**Additional context**

My staging server logs the following request body:

```
Received form request with body {h=[entry], content=[content], published=[2020-08-11T18:58:00+0100], post-status=[published], photo[]=[https://media.staging.jvt.me/1597168723787.png]}
```

**Comment by swentel** [comment]
Crap indeed, something missed with the account type refactoring. Worked still fine when not using the media endpoint (which I do), so I didn't see it immediately.

Fixed now. I'm tracking one more issue, normally there's a new release around the end of the week with this fix then!
