### ISSUE TITLE
Syndication targets not correctly updated when switching accounts while composing a post?

### ISSUE THREAD

**Issue by janboddez** [swentel/indigenous-android#403]
**Describe the bug**
Simply put, my endpoint returns a 400 error ("Unknown mp-syndicate-to targets: ...") when I switch accounts while I've already started creating a post and then hit send (with one of the syndication checkboxes selected, of course).

The target mentioned is, in fact, my other account's. (It's named the same as my main account's target, though.)

**To Reproduce**
1. Have two accounts with syndication targets. (My different accounts' targets have the same _name_, too. Like, both accounts have, say, a "Mastodon" target, with the target URLs themselves being different.)
2. Start, e.g., a new note.
3. Switch to the other account.
4. Check the syndication box, and hit send.
5. Watch the error message appear.

**Expected behavior**
"Post success."

**Smartphone (please complete the following information):**
 - Device: some OPPO, Android 10

**Additional info**
I actually renamed the targets (on the server's end) to their actual URLs and refreshed (or reconnected, not entirely sure) the account. When I then switched accounts in the middle of writing something, I _did_ see the checkbox labels get switched correctly--can't tell if posting worked, though. It almost definitely does _not_ work when the targets are named the same. (When they are the same, I can of course not tell if the labels are updated, or if nothing happens at all.)

I'm thinking either the labels are updated correctly but the underlying targets aren't, or it has to do with the fact that they're named the same (yet belong to different accounts).

I don't know for sure if it happens in both directions, either, but I'm definitely seeing it happen when I switch from my main account to a second account (again, while I've already started creating a note, reply, or whatever).

**Comment by swentel** [comment]
oh, interesting, I remember that I see it switching, however, I never did an actual post, so I'll see if I can reproduce. Thanks for letting this know! :)

**Comment by janboddez** [comment]
Fun thing is, if you switch to a non-default account, write something, and tick one of the syndication boxes _and then uncheck it_, Indigenous will still fail to submit the post.

**Comment by swentel** [comment]
The fix is easy, but it took me a while to figure it out :)

**Comment by janboddez** [comment]
Hadn't really followed up, but the issue is still present. The in-app syndication target list is updated, but under the hood, something is still off.

To reproduce: I start creating a Note, switch the account at the top, check the first syndication target, then hit Send. My server then complains about the missing syndication target (`Micropub Error: 400 invalid_request - Unknown mp-syndicate-to targets: ...`), which is in fact the first target of my _main account_.

**Comment by janboddez** [comment]
Oh, wait. This hasn't been released yet, has it? If so: sorry!

**Comment by swentel** [comment]
@janboddez Indeed, not released yet, I'm working on alternative notifications via MQTT, but bit behind on that.
If I don't get any further soon, I'll trigger a new release so this gets out at least :)
