### ISSUE TITLE
.github/ISSUE_crtn32002/bug_report.md

### ISSUE THREAD

**Issue by crtn32002** [swentel/indigenous-android#408]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Android version: [e.g. 8.0.0]

**Additional context**
Add any other context about the problem here. This may contain strack traces if available

**Comment by swentel** [comment]
hmm not sure what the bug is, so feel free to reopen when there's one :)
