### ISSUE TITLE
Creating a repost fails with 403 unreadable message

### ISSUE THREAD

**Issue by smaffulli** [swentel/indigenous-android#411]
Trying to publish a repost from Indigenous I noticed the 403 error in the screenshot. One of the issues is that the error message is not fully readable.

I tried then removing the account and authorizing it again. The message I get is "expired token". Again, the error message is not fully visible. 

Any suggestions of what to do next?
![photo_2020-11-01_18-41-50](https://user-images.githubusercontent.com/1348736/97824861-64c59880-1cbd-11eb-93fa-da309cdc4d21.jpg)
![photo_2020-11-01_18-42-27](https://user-images.githubusercontent.com/1348736/97824884-70b15a80-1cbd-11eb-8f81-15bbe5a3ad05.jpg)

**Comment by jamietanna** [comment]
Are you able to give <code>adb logcat</code> a go? (I can try and help with how to get it started) I've found it lets you see the full error response, and that may help track it down.

To confirm, you logged out of your account, restarted the app to make sure you were logged out? Then re-authorized, and it's still 403ing?

(Originally published at: https://www.jvt.me/mf2/2020/11/mmzse/)

**Comment by smaffulli** [comment]
> To confirm, you logged out of your account, restarted the app to make sure you were logged out? Then re-authorized, and it's still 403ing?

correct

If you could give me some pointers to get started, I confirm I can `adb logcat` but I don't know how to filter the events for Indiegenous only.

**Comment by jamietanna** [comment]
Hmm,those are definitely all the logs for that pid during the period where you get the error?

(Originally published at: https://www.jvt.me/mf2/2020/12/2h089/)

**Comment by smaffulli** [comment]
Correct, the error is this one, I don't see more details:

```12-07 17:57:42.299  7745  9318 E Volley  : [2988] BasicNetwork.performRequest: Unexpected response code 403 for https://maffulli.net/wp-json/micropub/1.0/endpoint```

If it helps, this is the error I get when using Quill:

```
HTTP/1.1 403 Forbidden
Server: openresty
Date: Tue, 08 Dec 2020 17:26:52 GMT
Content-Type: application/json; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
Vary: Accept-Encoding
X-Robots-Tag: noindex
Link: <https://maffulli.net/wp-json/>; rel="https://api.w.org/"
X-Content-Type-Options: nosniff
Access-Control-Expose-Headers: X-WP-Total, X-WP-TotalPages, Link
Access-Control-Allow-Headers: Authorization, X-WP-Nonce, Content-Disposition, Content-MD5, Content-Type
Vary: User-Agent
Access-Control-Allow-Origin: *
X-Hosted-By: DreamPress

{"code":"forbidden","message":"Unauthorized","data":{"status":403}}
```

It's possible that the issue is on the hosting side but where that would be is still largely unknown. I've been trying to analyze this with the help of indieweb-wordpress channel on IRC, too. If you have any idea of where to look next, I'm all ears.

**Comment by smaffulli** [comment]
well.. the problem just went away. Maybe the issue was with the hosting company and they changed something. Problem gone.
