### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [swentel/indigenous-android#414]
You can add Screenshots for F-Droid, too, if you want.

https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

https://gitlab.com/snippets/1895688

**Comment by swentel** [comment]
Yep, will do this in #402 :)

**Comment by Korb** [comment]
> Yep, will do this in #402 :)

There are still no screenshots of [the Indigenous app on F-Droid](https://f-droid.org/en/packages/com.indieweb.indigenous/).
