### ISSUE TITLE
Media attachments from a followed mastodon microformats feed are not displayed.

### ISSUE THREAD

**Issue by jk-na** [swentel/indigenous-android#415]
**Describe the bug**
Media attachments from a followed mastodon microformats feed are not displayed.

Media attachments are displayed if following the equivalent RSS feed, however then user account name and avatar are not correctly displayed and the message is partially displayed (as a title) as well as subsequently fully displayed, so not as pretty.

This is using my indieweb site as the account and aperture for following the feeds, I'm not sure if this is an issue with indigenous, with aperture or if mastodon need to improve their microformats support.

**To Reproduce**
1. Add a channel to aperture and follow a microformats feed of a mastodon user
2. Wait for them to post an image or other attachment (or if possible do so with your own mastodon account)
3. See the lack of image attachment
4. Do the same as above with their RSS feed, see the image attachment but note the format of the rest of the post.

**Expected behavior**
Attachments from the mastodon micfoformats feed to be displayed.

**Screenshots**
If required I can take some and attach.

**Smartphone (please complete the following information):**
 - Device: HTC U Ultra
 - Android version: LineageOS 18 which equates to Android 11

**Additional context**
Nothing to add.

**Comment by swentel** [comment]
My gut feeling is that this is something with aperture, ultimately something in the XRay package which parses the feeds. Indigenous itself doesn't parse anything, it just receives the data. So if there's nothing in it, well, then I can't display it :)

There's a test site at http://xray.p3k.io/ which allows you to see the output when XRay parses a feed.

**Comment by jk-na** [comment]
OK, that makes sense, testing a post with photos attached does seem to include the photos on xray.

https://xray.p3k.io/parse?url=https%3A%2F%2Fmstdn.social%2F%40JonathanMBR%2F105865534992829993&pretty=true

```
{
    "data": {
        "type": "entry",
        "url": "https://mstdn.social/@JonathanMBR/105865534992829993",
        "published": "2021-03-10T12:37:47+00:00",
        "content": {
            "text": "Because of their nomadic nature, Turkana people build temporary houses like these.",
            "html": "<p>Because of their nomadic nature, Turkana people build temporary houses like these.</p>"
        },
        "photo": [
            "https://mstdn.social/system/media_attachments/files/105/865/528/538/663/610/original/bca8672dce9a6436.jpeg",
            "https://mstdn.social/system/media_attachments/files/105/865/528/580/457/542/original/99dfc5506b8a0de5.jpeg"
        ],
        "author": {
            "type": "card",
            "name": "Jonathan Mburugu",
            "url": "https://mstdn.social/@JonathanMBR",
            "photo": "https://mstdn.social/system/accounts/avatars/000/179/051/original/f8e979470ecfd9e4.jpg",
            "nickname": "JonathanMBR"
        },
        "post-type": "photo"
    },
    "url": "https://mstdn.social/@JonathanMBR/105865534992829993",
    "code": 200,
    "source-format": "activity+json"
}
```
Is it possibly in an unexpected format?  I'm happy to raise a ticket with aperture or xray, just confirming that all should be well at this end.

**Comment by jk-na** [comment]
I've checked with monocle and with together and the same lack of photos is happening via both, so will close this, thank you for the pointer.
