### ISSUE TITLE
Display event post and allow RSVP

### ISSUE THREAD

**Issue by swentel** [swentel/indigenous-android#42]
Depends on how fast I can get https://github.com/swentel/indieweb/issues/154 in

**Comment by cweiske** [comment]
.. and add a calendar entry when RSVPing "yes" :)

**Comment by swentel** [comment]
Oh yes, good idea!

**Comment by swentel** [comment]
I've split the add to calendar part in a different issue (#62), it's trickier than I thought it would be.
RSVP already works, just need to add it now in the timeline for microsub
