### ISSUE TITLE
Offline posting: Save as draft

### ISSUE THREAD

**Issue by swentel** [swentel/indigenous-android#43]
Either a dedicated checkbox / button
also show when there's no connection in popup when hitting post button

The difference with #79 is that here the post is saved in indigenous, so not send yet to the server

caching of channels and items will happen in #120

**Comment by swentel** [comment]
First post types are supported: note, article and reply

**Comment by EdwardHinkle** [comment]
Currently the iOS version handles this by only saving the most recent draft. If you start typing and then close the post window with content but not posting it, it asks if you would like to save or delete the draft. Next time you open it, it starts with the saved post

**Comment by EdwardHinkle** [comment]
I do want to expand that to cover more than one saved draft though.

**Comment by swentel** [comment]
Noticed while testing this feature: when editing a draft, set the 'Save as draft' checkbox to checked so you don't post by accident.

**Comment by ngm** [comment]
This is so rad! I'm just heading on holiday for a couple of days to somewhere with patchy connectivity, so should be able to give it a test there.

**Comment by swentel** [comment]
I've been testing this myself now for a couple of days and it's pretty cool
One thing that needs to be stored as well is the syndication targets I guess.

And I'm going to add it to all other post types, just makes sense :)

**Comment by ngm** [comment]
I've been using this, very cool!

One thing - if you save a draft, then edit it and post it, it stays in the list of draft posts until you navigate away and then navigate back to the list of drafts.

**Comment by swentel** [comment]
All post types can now be saved as draft, including all properties. This also includes coordinates, so you can save and post later when you are on a different location.
