### ISSUE TITLE
Fetch syndications on authentication and get them from q=config as well

### ISSUE THREAD

**Issue by swentel** [swentel/indigenous-android#55]

**Comment by dshanske** [comment]
https://tiny.n9n.us/?micropub=endpoint&q=config 

The WordPress micropub endpoint at the moment(though I'd like to change it), itself is a query string. Therefore, it isn't reading it correctly.

**Comment by swentel** [comment]
So syndications are now saved on authentication.. URL for q=syndicate-to will work.

But I need to add q=config as well .. will be for tomorrow.

**Comment by swentel** [comment]
Added dedicated issue for q=config
closing this one, should be fine now, release probably this weeked before the big multiple accounts refactoring

**Comment by swentel** [comment]
needed extra commit in https://github.com/swentel/indigenous-android/commit/5c4f6dc32460b3549115343656ec217c6e46687b
