### ISSUE TITLE
Send form-urlencoded where there is no binary in the request, form-data otherwise

### ISSUE THREAD

**Issue by cweiske** [swentel/indigenous-android#59]
Indigenous does not seem to send a `Content-type` header when POSTing a like or reply to the micropub server.

https://commentpara.de/ checks the incoming data type and rejects the request when it's neither `application/x-www-form-urlencoded` nor `application/json`. Currently all Indigenous submissions are rejected because the type header is missing.

**Comment by swentel** [comment]
Oh, interesting. I'll add application/x-www-form-urlencoded asap as that's the default at the moment.

**Comment by swentel** [comment]
Oh sweet irony, adding that completely breaks it on my end, will do a quick fix there and then commit this so testing can go on.

**Comment by swentel** [comment]
So investigating some more: I'm always sending 'multipart/form-data' because there's a possibility a file is attached. However, that's only for a note and article, so we could check: if no photo, send urlencoded, otherwise, use form-data.  What I'm wondering, does posting a note fail too @cweiske ? Or does commentpara.de not support that on its micropub endpoint ?

**Comment by cweiske** [comment]
commentpara.de does not support notes at all, since it's made for reply-type posts only.

**Comment by swentel** [comment]
Hehe, cool. However, It's still an oversight of me to send multipart/form-data when it's not really needed.

When looking at the docs of quill (https://quill.p3k.io/), the headers are different depending on:

- if it has photo (or other binaries), send multipart/form-data
- if not, send url-encoded

So this still needs to fixed here in the app too :)

**Comment by swentel** [comment]
Updated the title a bit to reflect better what needs to be fixed.

**Comment by swentel** [comment]
Given this some more thought and going to leave this as is. It doesn't make that much difference and has more code overhead.

**Comment by hirusi** [comment]
Could I please request this feature at all again? The Micropub server I am using (indiekit) expects either JSON or url-encoded form data for notes, likes, replies etc. When publishing to the media endpoint, it expects multipart. This seems like a fair requirement on this project's part.

**Comment by swentel** [comment]
sounds fair. Related with #379 a bit, especially with my comment. Reopening to make sure I don't forget it.

**Comment by swentel** [comment]
Ready in dev. Will test for a week now or so, new release beginning of august or so.
