### ISSUE TITLE
Make it easier to like a page

### ISSUE THREAD

**Issue by cweiske** [swentel/indigenous-android#61]
liking a browser page on android takes 4 steps now:
 
1. Share
2. Indigenous
3. Like
4. Send

a bit much in my eyes
I don't think that people add tags to likes; this is an unnecessary step IMO
maybe indigenous could add explicit reply and like buttons in the android share screen

**Comment by pstuifzand** [comment]
It is possible to create extra activities for "like", however I noticed that not all apps supports this. I think Twitter will only shows different apps, and not the specific actions.

(Originally published at: https://p83.nl/p/589)

**Comment by swentel** [comment]
This is now possible. There is a settings screen which allows you to expose like/bookmark/repost/reply in the share intents. They are disabled by default. If you enable, they will start showing up (you will have to restart the browser though), and a like/bookmark/repost will now send immediately.

New release is out, so will be in a few minutes or hours. 

(done in https://github.com/swentel/indigenous-android/commit/21c8e1ca82d6eb36a3a3257139cc9ddee78d94b2)

**Comment by swentel** [comment]
Forgot to push the rollout button, damn interface.
Should be available in a few minutes now.
