### ISSUE TITLE
Design & feeling

### ISSUE THREAD

**Issue by swentel** [swentel/indigenous-android#70]
My colleague Leen has created some designs for the app. I gave her all freedom, so you never know what's going to happen then of course :) She also played with multiple variants of colors. We can choose one. (it's always possible to even implement different themes, but I wouldn't go that far tbh)

But overall I like it :)

Personal preference is for the red variant for color.
For the logo, my personal preference is the first red one

**Comment by swentel** [comment]
Her idea of the main logo

![artboard](https://user-images.githubusercontent.com/168466/39956940-b3d1a8e8-55ea-11e8-8cc9-0e19d1b28623.jpg)
![artboard 4](https://user-images.githubusercontent.com/168466/39956941-b3ee9610-55ea-11e8-8885-e73147c80f8a.jpg)
![artboard 3](https://user-images.githubusercontent.com/168466/39956942-b40b387e-55ea-11e8-99cb-5a5292a9ba24.jpg)
![a](https://user-images.githubusercontent.com/168466/39956943-b42f9b92-55ea-11e8-90bf-ab8fc1074450.jpg)
![artboard 2](https://user-images.githubusercontent.com/168466/39956944-b4498336-55ea-11e8-975e-11a1d7d4b303.jpg)

**Comment by swentel** [comment]
Main screens

![mobile](https://user-images.githubusercontent.com/168466/39956955-f3b048ac-55ea-11e8-80e7-f66596675857.jpg)
![mobile copy 2](https://user-images.githubusercontent.com/168466/39956957-f7f99cb0-55ea-11e8-8948-d39bca15bbf3.jpg)
![mobile copy 3](https://user-images.githubusercontent.com/168466/39956959-01aca3ba-55eb-11e8-8b31-464e718df532.jpg)

![mobile copy 4](https://user-images.githubusercontent.com/168466/39956962-0f907c04-55eb-11e8-95bc-7f12c8691163.jpg)
![mobile copy 7](https://user-images.githubusercontent.com/168466/39956965-1d754e1c-55eb-11e8-996e-1565c13500cf.jpg)
![mobile copy 5](https://user-images.githubusercontent.com/168466/39956963-12934ea4-55eb-11e8-8112-c5f567e054c3.jpg)

![mobile copy 8](https://user-images.githubusercontent.com/168466/39956967-32ab063c-55eb-11e8-975e-bd8020c700dd.jpg)
![mobile copy 11](https://user-images.githubusercontent.com/168466/39956971-359bf1a8-55eb-11e8-93ec-1c4a2554df25.jpg)
![mobile copy 9](https://user-images.githubusercontent.com/168466/39956973-383c5e7a-55eb-11e8-9601-105a9ec70f2a.jpg)

**Comment by swentel** [comment]
Icons for all actions, post types etc - she created them with fontello, but these can be extracted to svg's.

[fontello-c653baa6.zip](https://github.com/swentel/indigenous-android/files/1997568/fontello-c653baa6.zip)

**Comment by swentel** [comment]
Pinging @EdwardHinkle (if that works from here)

**Comment by EdwardHinkle** [comment]
I agree, I like the first one. For what it’s worth I’m working on another Micropub app that has a green theme, so I’d probably stay away from that one if possible 🙂 I think that first one looks nice and we could make the blue an alternate theme option

**Comment by EdwardHinkle** [comment]
Did she provide a color palette for the Red and Blue variants? I need to do some styling updates in the iOS version over the next couple of weeks and I'd be happy to transition my red into the red palette that she did

**Comment by EdwardHinkle** [comment]
Sounds good! No rush :) Thanks!

**Comment by EdwardHinkle** [comment]
Hey, just checking in on if you have the colors yet :)

**Comment by swentel** [comment]
I completely lost track of that, but I asked today, so hoping to get something by the end of the week! :)

**Comment by EdwardHinkle** [comment]
Just checking in 😃

**Comment by swentel** [comment]
pinged my colleague again as well :)

**Comment by swentel** [comment]
Ok, sorry for the delay, she's been swamped in work, and I'm leaving on holiday for ten days now .. so will only be after july 1st.

You could use the colors from the screenshots of course and I think there are some helper programs that can generate a matching color pallette, so feel free to use them if you want those earlier :)

**Comment by EdwardHinkle** [comment]
Haha! I literally did just that today 😁😁

**Comment by EdwardHinkle** [comment]
No worries. Have a great holiday!

**Comment by swentel** [comment]
I only need the icon now, we can close this one
