### ISSUE TITLE
Check caching to login

### ISSUE THREAD

**Issue by swentel** [swentel/indigenous-android#73]
Yoroy is getting "We did not find the necessary rel links on your domain (authorization_endpoint, token_endpoint, micropub, microsub)" even though his headers look fine on the site

**Comment by yoroy** [comment]
One detail: he does not have httpS but http on his domain.
Tests via quill app do work.

**Comment by yoroy** [comment]
And… it works. Probably some caching issue somewhere.

**Comment by swentel** [comment]
will double check still though, but glad it's working

**Comment by swentel** [comment]
Seems to be fine, so let's leave this as is for now.
