### ISSUE TITLE
Allow to select which account to use when posting or sharing

### ISSUE THREAD

**Issue by swentel** [swentel/indigenous-android#78]
This can be done by adding a 'post as' dropdown at the top. Add a setting to set a default for this.

**Comment by dshanske** [comment]
Adding a note on this. When I share now, it doesn't make it clear which account it is set to. Is there any visual indicator of that you can add? Look at how many apps do it with a round icon?

**Comment by swentel** [comment]
This becomes tricky. I had a working prototype. But it felt weird. Given that all other features (channels, source, contact) really live per account, I'm going to close this one. https://github.com/swentel/indigenous-android/issues/244 is going to help better!
