### ISSUE TITLE
Allow post status

### ISSUE THREAD

**Issue by swentel** [swentel/indigenous-android#79]
usually only for article

**Comment by grantcodes** [comment]
Seems the same as #43 to me

**Comment by swentel** [comment]
I guess the subtle difference is that if you want to send it to the server and mark it as (un)published there. But yes, closely related, especially as long as there's no option to get posts from the server (although I guess 'query' could be used for that)

**Comment by swentel** [comment]
clarified #43 - that one is really about saving drafts in Indigenous, so not yet send to the server.

**Comment by grantcodes** [comment]
Ah ok, in app draft vs `post-status` on site.

Makes sense. Thanks for the clarification

**Comment by swentel** [comment]
https://github.com/swentel/indieweb/issues/46 is in, so we can start using this

**Comment by swentel** [comment]
This is in, will be available in next release
