### ISSUE TITLE
Allow sending location

### ISSUE THREAD

**Issue by swentel** [swentel/indigenous-android#8]

**Comment by dshanske** [comment]
Can you also support location visibility? https://indieweb.org/Micropub-extensions#Location_Visibility

**Comment by swentel** [comment]
aha interesting property.

I have location support now in the drupal plugin, going to start on adding it in the app, when it's less warm :)

**Comment by dshanske** [comment]
Is it less warm?

**Comment by swentel** [comment]
Hehe yes! it's a better few days!
Did some commits already, working on this one as we speak :)

**Comment by dshanske** [comment]
checkins. But I could see it sent on everything if someone wants.

**Comment by dshanske** [comment]
That's why I came up with a visibility setting. Sometimes it is not something you want to share

**Comment by swentel** [comment]
Sending location is now possible on note, event and article.

Finetuning the code a bit now. Visiblity is not available yet.

**Comment by swentel** [comment]
Closing this one. Created #97 as a separate dedicated issue.
