### ISSUE TITLE
Login Loop

### ISSUE THREAD

**Issue by zoglesby** [swentel/indigenous-android#84]
After the last update my phone is stuck in a loop logging into my site.  The app asks for a URL again, I provide it, login in, auth, get the message that it was good, and then I am taken back to the page asking for a URL. It was working fine prior to the most recent update, and is still working on another device.

The device that it is not working on in a Note 8 with Android 8.0 with the May 2018 security patches. Let me know if you need more info to troubleshoot this.

**Comment by zoglesby** [comment]
1) I have tried this and I did not help
2) The account is in the systems accounts list
3) I also have a microsub endpoint, running my own instance of Aperture

**Comment by swentel** [comment]
Ok, good to know that the account is in the accounts list, that at least gives me a good pointer to figure out the problem, or a solution :)

Thanks for that information!

**Comment by ngm** [comment]
I'm experiencing the same issue described here.  It seems like I auth successfully but I end up back on the authentication screen.

I see the messages:

* Validating code
* Authentication successful
* Syndication targets saved (I think, something similar anyway!)

To answer the previous questions:

* I have cleared the app data but it didn't solve the issue
* I see the Indigenous account in the accounts overview screen
* I don't currently have a microsub endpoint (I plan to add one soon though :) )

**Comment by swentel** [comment]
Interesting, so for some reason the user is not saved in the user data accounts.

Emulator tests don't fail on this, but I /think/ I have a workaround, will ship a potential solution over the weekend normally.

**Comment by ngm** [comment]
It worked!  Amazing, thanks so much for resolving :)

(my first note via Indigenous - https://doubleloop.net/2018/09/07/3376/)

**Comment by swentel** [comment]
Awesome!

I've added this to the README - I should probably add this to the site as well.
