### ISSUE TITLE
Add support for Listen posts in the share screen

### ISSUE THREAD

**Issue by EdwardHinkle** [swentel/indigenous-android#85]
To aid in the support of encouraging IndieWeb podcasts, I think it would be great to have both Indigenous for iOS and Indigenous for Android support listen posts. I've been beta testing this for awhile on my iOS version and it works pretty well. The problem set is as follows:

- A user is listening to a podcast in their favorite podcast player
- User presses the share episode button when they are near the end of the podcast
- User selects Indigenous
- User selects "Listen"
- Indigenous takes the URL provided by the podcast player and has to parse the page to find the Podcast Episode permalink
- Indigenous creates a Listen post via micropub with the listen url being the podcast episode permalink from the parsed page rather than the URL provided by the podcast player

Some examples of the URLs provided by podcast players:
Pocket Cast: https://pca.st/Mr9N
(Overcast and Castro on iOS share something similar).

These initial urls are pages about a specific episode but they are essentially reposts without mf2 markup. I've built some HTML scrapping algorithms for both Overcast and Castro inside of my website's Micropub endpoint. I want to take that logic, add Pocket Casts scrapping support and embed it within my copy of XRay: https://xray.abode.pub/

Essentially allowing us to fetch this url: https://xray.abode.pub/parse?url=https%3A%2F%2Fpca.st%2FMr9N for a given podcast episode and instead of getting back type: unknown, that xray instance would parse Pocket Cast, Overcast and Castro urls and return audio post types with the url attribute being the permalink of the podcast episode. For example, for one of GWG's podcast episodes the permalink would end up being: https://david.shanske.com/2018/06/17/an-indieweb-podcast-episode-7-the-reverse-salmention/

This would allow a person to create a Reply, Like or Listen post in reply to podcasts while using whatever podcast player is their preferred instance.

One major question: Are there any other popular podcast players that we need to add support to?

Currently my list is:
- Castro (iOS)
- Overcast (iOS)
- Pocket Casts (iOS & Android)

Thoughts?

**Comment by Zegnat** [comment]
Another popular free & open-source podcatcher:

* [AntennaPod](http://antennapod.org/) (Android)

**Comment by Zegnat** [comment]
For the record: AntennaPod – when you “Share Link” on an episode – seems to get the link straight from the feed you are subscribed to. Quick test, I have searched iTunes (from within AntennaPod) for the Judge John Hodgman podcast. The found the same episode as I did for the Pocket Casts link above. The resulting URL is: http://feedproxy.google.com/~r/todayinthepast/~3/6xUlp6sj16E/wedding-clashers

**Comment by swentel** [comment]
Oh interesting. The Android version already supports listening to posts which have audio mf2 markup (but from the ones I'm testing currently, only that of Marty really works, the micro.blog markup isn't ok yet, although it would be pretty simple to fix that).

So being able to parse and post it to your own site sounds very interesting. I've been thinking whether we could make aperture a bit smareter this way: toggle an rss feed with audio (if you explicitly follow an audio rss) so that aperture stores this with an audio property. IIRC, the parsing also uses xray, so in the end, it probably ends up to the same thing. I'm going to setup aperture soon anyway, because I need to debug why my site isn't being refreshed in Aaron's instance (I know of another Drupal site which is fine, so it's something on my end, probably caching).

**Comment by klrabbit** [comment]
I use Podcast Addict on Android. It allows you to share Episode URL, episode description, location in episode and play in different app. If you need to know anything else let me know

**Comment by dshanske** [comment]
Wanted to bump listen posts, but in the UI. If you can't share, you can add album, artist, and title perhaps

**Comment by swentel** [comment]
So, what fields does the podcast contain:

- url
- title
- body

What else ? If I know the fields, I can create a UI and simpy send the values in a request.

**Comment by swentel** [comment]
Closing this for now. I don't have a need for it.

I don't use a podcast app (I actually use indigenous heh), so not sure what share elements would come in.

Pull requests welcome of course.
