### ISSUE TITLE
Add support for issue posts

### ISSUE THREAD

**Issue by dshanske** [swentel/indigenous-android#88]
Issue posts are basically replies with an explicit title.

**Comment by swentel** [comment]
So, if I just add a title field to the reply screen, that's good enough right ?

I thought about adding a separate one post type first in the micropub list, but then I'd have to add another icon on the microsub stream if you want to reply to an issue which seems a bit overkill.

I would also more or less take me 5 minutes to just add a title field to that activity :)

**Comment by dshanske** [comment]
If you are replying to an issue, that's a comment. That's fine. An issue is a reply to a repository only. But, you can address it the way you suggested, but replies aren't supposed to have names, so the layout might be better at the bottom.

**Comment by swentel** [comment]
right makes sense to put it at the bottom. cf attach - is the hint a bit too much ?

![screenshot_20180930-211142_indigenous](https://user-images.githubusercontent.com/168466/46261568-9f184680-c4f5-11e8-9910-19ae6a2c5a10.jpg)

**Comment by swentel** [comment]
ready - it's a different post type in the list. coming in next release :)
