### ISSUE TITLE
Cannot log in

### ISSUE THREAD

**Issue by davidmead** [swentel/indigenous-android#90]
I downloaded the .apk and installed it on my Pixel 2.

I can open the app, enter my URL, get the Wordpress authorization page, click 'Authorize' and it takes me back to the log in screen where the following error appears

`Authentication failed: Status code: 401; message: {"error":"invalid code","error_description":"Invalid authorization code"}`

![screenshot_20180630-143514](https://user-images.githubusercontent.com/1266930/42128441-becfe448-7c79-11e8-90e8-d8f03b3a6624.png)

Have tried this multiple times and get the same issue.  I do have the meta tag in my WP header and can use Together to read the couple of feeds I've added.

**Comment by swentel** [comment]
Hi David,

Hard to tell without more debugging information. I wonder whether @dshanske could add some debugging tips here or maybe where to look on the wordpress side of things.

I'm going to think in the mean time how I could get more debug information in the app too.

**Comment by EdwardHinkle** [comment]
There have been a variety of issues with Wordpress IndieAuth. I would say the first step, @davidmead would be to verify if you have version 3.0.2 for your IndieAuth plugin. If you do, then I would probably reach out with your issue on the Wordpress IndieWeb discussion channel (IRC or Slack), as I've seen several people talking about similar issues and several being resolved recently.

**Comment by davidmead** [comment]
@EdwardHinkle I just updated to 3.0.2 today.  I'll try logging in to the app tonight.

**Comment by dshanske** [comment]
We've been knocking the issues down as we discover them. I found at IWS that the problem for some people was a mismatch between http and https and pushed a fix. I am currently working on a major refactoring of the Micropub Endpoint that includes the capability to pass more data when there is a failure.
