### ISSUE TITLE
indigenous beta, login error

### ISSUE THREAD

**Issue by marwal88** [swentel/indigenous-android#92]
When using the app to log onto https://myuser.micro.blog, i get the server replying:
"The redirect URL and client URL must use the same hostname."

The uri indigenous is trying is this:
https://realize.be/indigenous-android.php&client_id=https://indigenous.abode.pub&me=https://myuser.micro.blog&scope=create+update+read+follow+channels&state=[some hex numbers]

**Comment by EdwardHinkle** [comment]
@swentel If you want to send me the PHP file, and you change the client_id to indigenous.abode.pub/android/ then I can put the PHP file as login.php so it would be client_id=indigenous.abode.pub/android/ and redirect_url=indigenous.abode.pub/android/login.php

**Comment by EdwardHinkle** [comment]
That should fix the Micro.blog issue

**Comment by swentel** [comment]
@EdwardHinkle ah that's probably related with https://github.com/EdwardHinkle/indigenous-ios/issues/172

But let me double check first, I'll let you know asap.

**Comment by EdwardHinkle** [comment]
Yep, that's it. I remembered discussing that. Forgot it was an issue with code :)

**Comment by EdwardHinkle** [comment]
https://github.com/EdwardHinkle/indigenous-ios/issues/172 was completed and closed.

**Comment by swentel** [comment]
Ok, awesome! Tested and redirect works fine, I'll release a new version asap, I'll ping again when it's out.

**Comment by swentel** [comment]
pushed new release, should be available soon, hopefully that fixes it!
