### ISSUE TITLE
Crash when pressing 'Sign In'

### ISSUE THREAD

**Issue by ngm** [swentel/indigenous-android#99]
The app crashes when trying to Sign In.  I enter my URL https://doubleloop.net where it says http://example.com, press Sign In, and it crashes there.  I'm on an old version of Android (Lollipop), I don't know if that has anything to do with it.

(If there's more debug info I can provide, let me know)

**Stack trace**

> android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag.  Is this really what you want?
at
android.app.ContextImpl.startActivity(ContextImpl.java:1258)
at
...
...
...
at
com.indieweb.indigenous.indieauth.IndieAuthActivity $1.onClick(IndieAuthActivity.java:127)

**Device Info**
* Sony Xperia Z1 Compact (D5503)
* SDK version: 22
* Release: 5.1.1

**App info**
* 0.11 from Google Play

**Comment by swentel** [comment]
So good news, I can reproduce this in an emulator. Will check what the best fix is now!

**Comment by swentel** [comment]
I've pushed a new release to the app store. Signing in worked on the emulator and micropub/microsub screens worked fine, so I think it should work now! :)

**Comment by ngm** [comment]
Awesome, thanks - the crash is fixed, thanks for the quick update :+1:
I do have another problem but I'll log in a separate issue.

**Comment by swentel** [comment]
Ok, cool will close then, thanks for reporting back!
